# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bangs) {transformation: [-0.9934f,-0.1143f,0f,0.0023f,-0.1143f,0.9934f,0f,0.438f,0f,0f,-1f,0.2586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bangs_l) {transformation: [-0.9997f,-0.0252f,-0.0009f,-0.2138f,-0.0253f,0.9991f,0.0342f,0.3178f,0f,0.0342f,-0.9994f,0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bangs_r) {transformation: [-0.9993f,-0.0379f,-0.0013f,0.2434f,-0.0379f,0.9987f,0.0342f,0.3178f,0f,0.0342f,-0.9994f,0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_pupil2) {transformation: [-1f,0f,0f,-0.0294f,0f,1f,0f,0.3719f,0f,0f,-1f,0.5243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_pupil) {transformation: [-1f,0f,0f,0.1412f,0f,1f,0f,0.1482f,0f,0f,-1f,0.2622f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_pupil2) {transformation: [-1f,0f,0f,-0.0576f,0f,1f,0f,0.3719f,0f,0f,-1f,0.5243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_pupil) {transformation: [-1f,0f,0f,-0.1327f,0f,1f,0f,0.1531f,0f,0f,-1f,0.2606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_ear) {transformation: [-0.9902f,-0.1394f,0f,-0.2939f,-0.1394f,0.9902f,0f,0.2347f,0f,0f,-1f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_ear) {transformation: [-0.9902f,0.1394f,0f,0.2939f,0.1394f,0.9902f,0f,0.2347f,0f,0f,-1f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}