# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.reverend_sceptre.root] run return 0
execute if entity @s[tag=aj.reverend_sceptre.animation.reverend_sceptre_standby.playing] run function animated_java:reverend_sceptre/animations/reverend_sceptre_standby/zzz/on_tick
execute if entity @s[tag=aj.reverend_sceptre.animation.reverend_sceptre_right_click.playing] run function animated_java:reverend_sceptre/animations/reverend_sceptre_right_click/zzz/on_tick
execute if entity @s[tag=aj.reverend_sceptre.animation.reverend_sceptre_right_ability.playing] run function animated_java:reverend_sceptre/animations/reverend_sceptre_right_ability/zzz/on_tick
execute if entity @s[tag=aj.reverend_sceptre.animation.reverend_sceptre_left_click.playing] run function animated_java:reverend_sceptre/animations/reverend_sceptre_left_click/zzz/on_tick
execute on passengers run rotate @s ~ ~