# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:archdemon/animations/pause_all
tag @s add aj.archdemon.animation.sprint_start_run.playing
scoreboard players set @s aj.sprint_start_run.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:archdemon/animations/sprint_start_run/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only