# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add new.mainhand_item
data modify entity @s view_range set value 0.01
data modify entity @s teleport_duration set value 1