# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.piglin_girl.node.chest] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_chest
execute on passengers if entity @s[tag=aj.piglin_girl.node.tail2] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_tail2
execute on passengers if entity @s[tag=aj.piglin_girl.node.tail] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_tail
execute on passengers if entity @s[tag=aj.piglin_girl.node.skirt] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_skirt
execute on passengers if entity @s[tag=aj.piglin_girl.node.skirt1] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_skirt1
execute on passengers if entity @s[tag=aj.piglin_girl.node.skirt2] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_skirt2
execute on passengers if entity @s[tag=aj.piglin_girl.node.body1] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_body1
execute on passengers if entity @s[tag=aj.piglin_girl.node.r_weapon] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_r_weapon
execute on passengers if entity @s[tag=aj.piglin_girl.node.r2] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_r2
execute on passengers if entity @s[tag=aj.piglin_girl.node.r1] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_r1
execute on passengers if entity @s[tag=aj.piglin_girl.node.l2] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_l2
execute on passengers if entity @s[tag=aj.piglin_girl.node.l1] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_l1
execute on passengers if entity @s[tag=aj.piglin_girl.node.rl2] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_rl2
execute on passengers if entity @s[tag=aj.piglin_girl.node.rl1] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_rl1
execute on passengers if entity @s[tag=aj.piglin_girl.node.ll2] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_ll2
execute on passengers if entity @s[tag=aj.piglin_girl.node.ll1] at @s run function animated_java:piglin_girl/variants/heavy_hurt/zzz/apply_to_node_ll1
return 1