# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_npc/zzz/summon/locators_on_summon/zzz/0 with entity @s data.locators.locator7
data modify entity @s data.uuids append from storage animated_java:temp uuids