# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.boss_box.root] run return 0
execute if entity @s[tag=aj.boss_box.animation.open_box.playing] run function animated_java:boss_box/animations/open_box/zzz/on_tick
execute on passengers run rotate @s ~ ~