# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:washing_machice/animations/default/zzz/apply_frame {frame: 5}
scoreboard players add @s aj.default.frame 1