# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify storage animated_java:temp args merge from entity @s data.locators.$(name)
function animated_java:pink_star_skill1/zzz/at_locator/execute_at_transform with storage animated_java:temp args