# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.gray_battle_boss_weapon.animation.battle_spawn.playing
tag @s remove aj.gray_battle_boss_weapon.animation.battle_ranged_greatsword.playing
tag @s remove aj.gray_battle_boss_weapon.animation.battle_ranged_sword_beam.playing
tag @s remove aj.gray_battle_boss_weapon.animation.battle_melee_2.playing
tag @s remove aj.gray_battle_boss_weapon.animation.battle_melee_3.playing
tag @s remove aj.gray_battle_boss_weapon.animation.battle_melee_4.playing