# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bangs) {transformation: [-1f,0f,0f,0.0023f,0f,1f,0f,0.438f,0f,0f,-1f,0.2586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bangs_l) {transformation: [-1f,0f,0f,-0.2138f,0f,1f,0f,0.3178f,0f,0f,-1f,0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bangs_r) {transformation: [-1f,0f,0f,0.2434f,0f,1f,0f,0.3178f,0f,0f,-1f,0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_pupil2) {transformation: [0f,0f,0f,-0.0294f,0f,0f,0f,0.3719f,0f,0f,0f,0.5243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_pupil) {transformation: [-1f,0f,0f,0.1412f,0f,1f,0f,0.1482f,0f,0f,-1f,0.2622f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_eye) {transformation: [-1f,0f,0f,0.1404f,0f,1f,0f,0.2266f,0f,0f,-1f,0.2597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_eyebrow) {transformation: [-0.9962f,-0.0872f,0f,0.1404f,-0.0872f,0.9962f,0f,0.2119f,0f,0f,-1f,0.2646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_pupil2) {transformation: [0f,0f,0f,-0.0576f,0f,0f,0f,0.3719f,0f,0f,0f,0.5243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_pupil) {transformation: [-1f,0f,0f,-0.1327f,0f,1f,0f,0.1531f,0f,0f,-1f,0.2606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_eye) {transformation: [-1f,0f,0f,-0.1387f,0f,1f,0f,0.2266f,0f,0f,-1f,0.263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_eyebrow) {transformation: [-0.9962f,0.0872f,0f,-0.1384f,0.0872f,0.9962f,0f,0.2119f,0f,0f,-1f,0.2646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_ear) {transformation: [-1f,0f,0f,-0.2939f,0f,1f,0f,0.2347f,0f,0f,-1f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_ear) {transformation: [-1f,0f,0f,0.2939f,0f,1f,0f,0.2347f,0f,0f,-1f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_all) {transformation: [-1f,0f,0f,-0.0006f,0f,1f,0f,0.2888f,0f,0f,-1f,0.0848f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}