# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bangs) {transformation: [-0.5f,0f,0f,0.0009f,0f,0.5f,0f,0.2072f,0f,0f,-1f,0.2586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bangs_l) {transformation: [-0.5f,0f,0f,-0.1072f,0f,0.5f,0f,0.1471f,0f,0f,-1f,0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bangs_r) {transformation: [-0.5f,0f,0f,0.1214f,0f,0.5f,0f,0.1471f,0f,0f,-1f,0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_pupil2) {transformation: [0f,0f,0f,-0.015f,0f,0f,0f,0.1741f,0f,0f,0f,0.5243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_pupil) {transformation: [-0.5f,0f,0f,0.0703f,0f,0.5f,0f,0.0623f,0f,0f,-1f,0.2622f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_eye) {transformation: [-0.5f,0f,0f,0.0699f,0f,0.5f,0f,0.1014f,0f,0f,-1f,0.2597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_eyebrow) {transformation: [-0.4981f,-0.0436f,0f,0.0699f,-0.0436f,0.4981f,0f,0.0941f,0f,0f,-1f,0.2646f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_l_pupil2) {transformation: [0f,0f,0f,-0.0291f,0f,0f,0f,0.1741f,0f,0f,0f,0.5243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_pupil) {transformation: [-0.5f,0f,0f,-0.0667f,0f,0.5f,0f,0.0647f,0f,0f,-1f,0.2606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_eye) {transformation: [-0.5f,0f,0f,-0.0696f,0f,0.5f,0f,0.1014f,0f,0f,-1f,0.263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_eyebrow) {transformation: [-0.4981f,0.0436f,0f,-0.0695f,0.0436f,0.4981f,0f,0.0941f,0f,0f,-1f,0.2646f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
$data merge entity $(bone_l_ear) {transformation: [-0.5f,0f,0f,-0.1473f,0f,0.5f,0f,0.1055f,0f,0f,-1f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_ear) {transformation: [-0.5f,0f,0f,0.1466f,0f,0.5f,0f,0.1055f,0f,0f,-1f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_all) {transformation: [-0.5f,0f,0f,-0.0006f,0f,0.5f,0f,0.1326f,0f,0f,-1f,0.0848f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}