# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gray_speed_lines.root] run return 0
scoreboard players add @s gray.exist 1
execute if score @s gray.exist matches 8.. run function animated_java:gray_speed_lines/remove/this
tag @s add gray.temp
execute as @a if score @s gray.id = @e[type=minecraft:item_display,tag=gray.temp,limit=1] gray.id at @s run tp @e[type=minecraft:item_display,tag=gray.temp,limit=1] ~ ~ ~
tag @s remove gray.temp
execute if entity @s[tag=aj.gray_speed_lines.animation.run.playing] run function animated_java:gray_speed_lines/animations/run/zzz/on_tick
execute on passengers run rotate @s ~ ~