# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pink_star_skill3_1 rig_hash set value '3d1178ff3b84d9cb12c2cfaeae19665198e99987f32372dbe40191b3de0f6343'
scoreboard objectives add aj.1.frame dummy