# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.head
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.leg1
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.leg2
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.leg3
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.leg4