# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:graud_golem/animations/pause_all
tag @s add aj.graud_golem.animation.step2.playing
scoreboard players set @s aj.step2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:graud_golem/animations/step2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only