# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:box rig_hash set value '0a048473cf1288af694b41d18d33dd723fbecb720211f7b28fc9266604d2f954'
scoreboard objectives add aj.open_box.frame dummy