# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle dust{color:[0.078,0.937,1.000],scale:1.8} ~ ~ ~ 5 0.5 5 0 10
particle minecraft:enchant ~ ~ ~ 5 1 5 1 15
particle minecraft:wax_off ~ ~2 ~ 5 3 5 1 6