# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.graud_golem.node.core] at @s run function animated_java:graud_golem/variants/golem_hurt/zzz/apply_to_node_core
execute on passengers if entity @s[tag=aj.graud_golem.node.case] at @s run function animated_java:graud_golem/variants/golem_hurt/zzz/apply_to_node_case
execute on passengers if entity @s[tag=aj.graud_golem.node.plate] at @s run function animated_java:graud_golem/variants/golem_hurt/zzz/apply_to_node_plate
execute on passengers if entity @s[tag=aj.graud_golem.node.ball] at @s run function animated_java:graud_golem/variants/golem_hurt/zzz/apply_to_node_ball
return 1