# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:spell_extra rig_hash set value '186ac40fc54a9df49e0c280bade25e0dcd11b9a29c3bd8f42e8acee4d603b788'
scoreboard objectives add aj.use.frame dummy