# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.run2.frame matches 16.. run scoreboard players set @s aj.run2.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.run2.frame
execute at @s run function animated_java:big_hoglin/animations/run2/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.run2.frame 1