# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:calamity_treant/animations/calamity_treant_walk/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.calamity_treant_walk.frame 1