# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone2) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,0.7969f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,1.125f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,1.6406f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,1.3594f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone4) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,1.9682f,0f,0f,1.5f,-0.0102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone5) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,0.4688f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,0.2344f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,1.1016f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone8) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,1.8281f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone9) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,0.7266f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone10) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,1.4063f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone11) {transformation: [1.5f,0f,0f,0f,0f,1.5f,0f,0f,0f,0f,1.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0.5625 ^1.6875 ^0.5625 rotated ~180 ~0 run function animated_java:gray_sandstorm/animations/sandstorm/zzz/frames/15_locator_locator5
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0 ^1.125 ^0 rotated ~180 ~0 run function animated_java:gray_sandstorm/animations/sandstorm/zzz/frames/15_locator_locator3
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0.5625 ^1.6875 ^-0.5625 rotated ~180 ~0 run function animated_java:gray_sandstorm/animations/sandstorm/zzz/frames/15_locator_locator
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^-0.5625 ^1.6875 ^-0.5625 rotated ~180 ~0 run function animated_java:gray_sandstorm/animations/sandstorm/zzz/frames/15_locator_locator4
data modify entity @s data merge value {"cameras":{},"locators":{"locator2":{"px":-0.5625,"py":1.6875,"pz":0.5625,"ry":180,"rx":0},"locator5":{"px":0.5625,"py":1.6875,"pz":0.5625,"ry":180,"rx":0},"locator3":{"px":0,"py":1.125,"pz":0,"ry":180,"rx":0},"locator":{"px":0.5625,"py":1.6875,"pz":-0.5625,"ry":180,"rx":0},"locator4":{"px":-0.5625,"py":1.6875,"pz":-0.5625,"ry":180,"rx":0}}}