# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl/animations/pause_all
tag @s add aj.piglin_girl.animation.axe_jump_end_late.playing
scoreboard players set @s aj.axe_jump_end_late.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:piglin_girl/animations/axe_jump_end_late/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only