# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gray_pharaoh_coffin rig_hash set value '259f69a6ce5562af7f4001f49a6056f6ed4451694b31db641afd1faee3423304'
scoreboard objectives add aj.shake.frame dummy
scoreboard objectives add aj.spawn.frame dummy