# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1529f,0.1784f,1.375f,0f,0.1784f,-1.1529f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.1146f,-0.2166f,1.32f,0f,-0.2166f,-1.1146f,0.11f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.6004f,0f,0f,0f,0.3281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.2981f,-0.3043f,3f,0f,-0.3043f,-1.2981f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3089f,0.2543f,3f,0f,0.2543f,-1.3089f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1324f,0.1752f,3.195f,0f,0.1752f,-1.1324f,0.2749f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.0801f,0.0831f,2f,0f,0.0831f,-1.0801f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1.966f,0f,-0.6234f,-0.25f,0f,2.0625f,0f,3.125f,0.6234f,0f,-1.966f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0117f,0f,0.6379f,0.25f,0f,2.1104f,0f,3.125f,-0.6379f,0f,-2.0117f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-1.1164473214112207e-16,"py":3.2229767098068205,"pz":0.9116484215600242,"ry":0,"rx":8.7962962962963}}}