# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1554f,0.1617f,1.375f,0f,0.1617f,-1.1554f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.1183f,-0.1964f,1.3252f,0f,-0.1964f,-1.1183f,0.0996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5937f,0f,0f,0f,0.2977f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3044f,-0.2761f,3f,0f,-0.2761f,-1.3044f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3132f,0.2306f,3f,0f,0.2306f,-1.3132f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1348f,0.1589f,3.2002f,0f,0.1589f,-1.1348f,0.249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.0807f,0.0753f,2f,0f,0.0753f,-1.0807f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1.9832f,0f,-0.5663f,-0.25f,0f,2.0625f,0f,3.125f,0.5663f,0f,-1.9832f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0293f,0f,0.5795f,0.25f,0f,2.1104f,0f,3.125f,-0.5795f,0f,-2.0293f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-1.0842011837948448e-16,"py":3.2373426830495666,"pz":0.8853174519785688,"ry":0,"rx":7.968749999999998}}}