# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1579f,0.1429f,1.375f,0f,0.1429f,-1.1579f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.1221f,-0.1736f,1.331f,0f,-0.1736f,-1.1221f,0.088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5868f,0f,0f,0f,0.2633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3108f,-0.2443f,3f,0f,-0.2443f,-1.3108f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3177f,0.2039f,3f,0f,0.2039f,-1.3177f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1372f,0.1404f,3.206f,0f,0.1404f,-1.1372f,0.2199f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.0813f,0.0665f,2f,0f,0.0665f,-1.0813f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0006f,0f,-0.5016f,-0.25f,0f,2.0625f,0f,3.125f,0.5016f,0f,-2.0006f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0471f,0f,0.5132f,0.25f,0f,2.1104f,0f,3.125f,-0.5132f,0f,-2.0471f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-1.0477015641042937e-16,"py":3.2535075905843915,"pz":0.8555132507052191,"ry":0,"rx":7.037037037037039}}}