# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1602f,0.1227f,1.375f,0f,0.1227f,-1.1602f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.1256f,-0.1491f,1.3373f,0f,-0.1491f,-1.1256f,0.0754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5804f,0f,0f,0f,0.2262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3167f,-0.2098f,3f,0f,-0.2098f,-1.3167f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3218f,0.1751f,3f,0f,0.1751f,-1.3218f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1395f,0.1205f,3.2123f,0f,0.1205f,-1.1395f,0.1886f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.0818f,0.057f,2f,0f,0.057f,-1.0818f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0169f,0f,-0.4313f,-0.25f,0f,2.0625f,0f,3.125f,0.4313f,0f,-2.0169f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0637f,0f,0.4414f,0.25f,0f,2.1104f,0f,3.125f,-0.4414f,0f,-2.0637f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-1.0082520696819364e-16,"py":3.2708632639668096,"pz":0.8233002939165159,"ry":0,"rx":6.035879629629631}}}