# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1651f,0.0603f,1.375f,0f,0.0603f,-1.1651f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.133f,-0.0733f,1.3565f,0f,-0.0733f,-1.133f,0.037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5668f,0f,0f,0f,0.1114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3293f,-0.1033f,3f,0f,-0.1033f,-1.3293f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3305f,0.0861f,3f,0f,0.0861f,-1.3305f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1443f,0.0592f,3.2315f,0f,0.0592f,-1.1443f,0.0926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.083f,0.028f,2f,0f,0.028f,-1.083f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0515f,0f,-0.2129f,-0.25f,0f,2.0625f,0f,3.125f,0.2129f,0f,-2.0515f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0991f,0f,0.2179f,0.25f,0f,2.1104f,0f,3.125f,-0.2179f,0f,-2.0991f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-8.856870586722819e-17,"py":3.3240078679813077,"pz":0.7232183673602314,"ry":0,"rx":2.9629629629629632}}}