# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1659f,0.0414f,1.375f,0f,0.0414f,-1.1659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.1343f,-0.0503f,1.3623f,0f,-0.0503f,-1.1343f,0.0254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5645f,0f,0f,0f,0.0764f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3314f,-0.0709f,3f,0f,-0.0709f,-1.3314f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.332f,0.0591f,3f,0f,0.0591f,-1.332f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1451f,0.0406f,3.2373f,0f,0.0406f,-1.1451f,0.0635f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.0832f,0.0192f,2f,0f,0.0192f,-1.0832f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0573f,0f,-0.1461f,-0.25f,0f,2.0625f,0f,3.125f,0.1461f,0f,-2.0573f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.1051f,0f,0.1495f,0.25f,0f,2.1104f,0f,3.125f,-0.1495f,0f,-2.1051f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-8.480855575398585e-17,"py":3.340073283816448,"pz":0.6925144116085787,"ry":0,"rx":2.03125}}}