# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail2) {transformation: [-1.4167f,0f,0f,-0.0312f,0f,1.0042f,-0.9993f,2.0232f,0f,-0.9993f,-1.0042f,-2.7595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,-0.0312f,0f,0.7676f,-0.6409f,2.6441f,0f,-0.6409f,-0.7676f,-2.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2_dirt) {transformation: [-1.5042f,0f,0f,0f,0f,1.1911f,0.9186f,0.8854f,0f,0.9186f,-1.1911f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2) {transformation: [-1.6875f,0f,0f,0f,0f,1.3363f,1.0306f,0.8854f,0f,1.0306f,-1.3363f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg2_dirt) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0432f,0f,0f,-1f,-1.2186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg2) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0432f,0f,0f,-1f,-1.2186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg_dirt) {transformation: [-1.3208f,0f,0f,1f,0f,1.3208f,0.0048f,2.0737f,0f,0.0048f,-1.3208f,-1.852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1.3125f,0f,0f,1f,0f,1.3125f,0.0048f,2.0737f,0f,0.0048f,-1.3125f,-1.852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg_dirt) {transformation: [-1.3208f,0f,0f,-1f,0f,1.3208f,0.0048f,2.0737f,0f,0.0048f,-1.3208f,-1.852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg2_dirt) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0432f,0f,0f,-1f,-1.2186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg2) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0432f,0f,0f,-1f,-1.2186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1.3125f,0f,0f,-1f,0f,1.3125f,0.0048f,2.0737f,0f,0.0048f,-1.3125f,-1.852f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}