# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail2) {transformation: [-1.4167f,0f,0f,-0.0312f,0f,1.0727f,-0.9253f,2.1844f,0f,-0.9253f,-1.0727f,-2.6728f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,-0.0312f,0f,0.8113f,-0.5847f,2.7509f,0f,-0.5847f,-0.8113f,-1.8869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2_dirt) {transformation: [-1.5042f,0f,0f,0f,0f,1.1227f,1.001f,0.8854f,0f,1.001f,-1.1227f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2) {transformation: [-1.6875f,0f,0f,0f,0f,1.2596f,1.123f,0.8854f,0f,1.123f,-1.2596f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg2_dirt) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0325f,0f,0f,-1f,-1.2173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg2) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0325f,0f,0f,-1f,-1.2173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg_dirt) {transformation: [-1.3208f,0f,0f,1f,0f,1.3128f,0.1456f,2.1247f,0f,0.1456f,-1.3128f,-1.7372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1.3125f,0f,0f,1f,0f,1.3045f,0.1447f,2.1247f,0f,0.1447f,-1.3045f,-1.7372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg_dirt) {transformation: [-1.3208f,0f,0f,-1f,0f,1.3128f,0.1456f,2.1247f,0f,0.1456f,-1.3128f,-1.7372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg2_dirt) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0325f,0f,0f,-1f,-1.2173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg2) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0325f,0f,0f,-1f,-1.2173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1.3125f,0f,0f,-1f,0f,1.3045f,0.1447f,2.1247f,0f,0.1447f,-1.3045f,-1.7372f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}