# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail2) {transformation: [-1.4167f,0f,0f,-0.0312f,0f,1.007f,-0.9964f,2.0298f,0f,-0.9964f,-1.007f,-2.7563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,-0.0312f,0f,0.7694f,-0.6387f,2.6485f,0f,-0.6387f,-0.7694f,-2.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2_dirt) {transformation: [-1.5042f,0f,0f,0f,0f,1.1885f,0.922f,0.8854f,0f,0.922f,-1.1885f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2) {transformation: [-1.6875f,0f,0f,0f,0f,1.3333f,1.0344f,0.8854f,0f,1.0344f,-1.3333f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg2_dirt) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0425f,0f,0f,-1f,-1.2184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg2) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0425f,0f,0f,-1f,-1.2184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg_dirt) {transformation: [-1.3208f,0f,0f,1f,0f,1.3208f,0.0105f,2.0757f,0f,0.0105f,-1.3208f,-1.8474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1.3125f,0f,0f,1f,0f,1.3125f,0.0104f,2.0757f,0f,0.0104f,-1.3125f,-1.8474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg_dirt) {transformation: [-1.3208f,0f,0f,-1f,0f,1.3208f,0.0105f,2.0757f,0f,0.0105f,-1.3208f,-1.8474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg2_dirt) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0425f,0f,0f,-1f,-1.2184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg2) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0425f,0f,0f,-1f,-1.2184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1.3125f,0f,0f,-1f,0f,1.3125f,0.0104f,2.0757f,0f,0.0104f,-1.3125f,-1.8474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}