# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail2) {transformation: [-1.4167f,0f,0f,-0.0312f,0f,1.0108f,-0.9926f,2.0385f,0f,-0.9926f,-1.0108f,-2.7519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,-0.0312f,0f,0.7718f,-0.6358f,2.6544f,0f,-0.6358f,-0.7718f,-2.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2_dirt) {transformation: [-1.5042f,0f,0f,0f,0f,1.185f,0.9265f,0.8854f,0f,0.9265f,-1.185f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2) {transformation: [-1.6875f,0f,0f,0f,0f,1.3294f,1.0394f,0.8854f,0f,1.0394f,-1.3294f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg2_dirt) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0417f,0f,0f,-1f,-1.2182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg2) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0417f,0f,0f,-1f,-1.2182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg_dirt) {transformation: [-1.3208f,0f,0f,1f,0f,1.3207f,0.018f,2.0784f,0f,0.018f,-1.3207f,-1.8413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1.3125f,0f,0f,1f,0f,1.3124f,0.0179f,2.0784f,0f,0.0179f,-1.3124f,-1.8413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg_dirt) {transformation: [-1.3208f,0f,0f,-1f,0f,1.3207f,0.018f,2.0784f,0f,0.018f,-1.3207f,-1.8413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg2_dirt) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0417f,0f,0f,-1f,-1.2182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg2) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0417f,0f,0f,-1f,-1.2182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1.3125f,0f,0f,-1f,0f,1.3124f,0.0179f,2.0784f,0f,0.0179f,-1.3124f,-1.8413f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}