# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail2) {transformation: [-1.4167f,0f,0f,-0.0312f,0f,1.0204f,-0.9827f,2.0609f,0f,-0.9827f,-1.0204f,-2.7406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,0f,0f,-0.0312f,0f,0.778f,-0.6282f,2.6695f,0f,-0.6282f,-0.778f,-1.9868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2_dirt) {transformation: [-1.5042f,0f,0f,0f,0f,1.1759f,0.938f,0.8854f,0f,0.938f,-1.1759f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2) {transformation: [-1.6875f,0f,0f,0f,0f,1.3192f,1.0523f,0.8854f,0f,1.0523f,-1.3192f,-0.4519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg2_dirt) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0396f,0f,0f,-1f,-1.2177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg2) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0396f,0f,0f,-1f,-1.2177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg_dirt) {transformation: [-1.3208f,0f,0f,1f,0f,1.3203f,0.0373f,2.0854f,0f,0.0373f,-1.3203f,-1.8255f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1.3125f,0f,0f,1f,0f,1.312f,0.0371f,2.0854f,0f,0.0371f,-1.312f,-1.8255f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg_dirt) {transformation: [-1.3208f,0f,0f,-1f,0f,1.3203f,0.0373f,2.0854f,0f,0.0373f,-1.3203f,-1.8255f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg2_dirt) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0396f,0f,0f,-1f,-1.2177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg2) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0396f,0f,0f,-1f,-1.2177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1.3125f,0f,0f,-1f,0f,1.312f,0.0371f,2.0854f,0f,0.0371f,-1.312f,-1.8255f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}