# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^4.25 ^2.125 ^0 ~0 ~0
data modify entity @s data.locators.leg2 merge value { px: 4.25, py: 2.125, pz: 0, ry: 0, rx: 0 }