# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^1.25 ^0 ^0 ~0 ~0
data modify entity @s data.locators.locator2 merge value { px: 1.25, py: 0, pz: 0, ry: 0, rx: 0 }