# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0.25 ^-0.5 ^0 ~0 ~0
data modify entity @s data.locators.hitbox1 merge value { px: 0.25, py: -0.5, pz: 0, ry: 0, rx: 0 }