# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gray_coffin rig_hash set value '99662454ab7cf66fc4901f24d928b1772ad1bdef2905ea335fb0b240808d5c26'
scoreboard objectives add aj.open.frame dummy