# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_arm) {transformation: [0.6996f,-0.4648f,-0.5427f,-0.3516f,0.3048f,0.8811f,-0.3617f,1.4825f,0.6463f,0.0877f,0.758f,-0.0443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sweep1) {transformation: [-0.0035f,-0.0003f,0f,-0.5856f,0.0004f,-0.0034f,0f,2.172f,-0.0002f,-0.0009f,0f,0.4868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_greatsword) {transformation: [-0.0023f,-0.0002f,0.0002f,-0.5855f,0.0002f,-0.0022f,0.0006f,2.1735f,-0.0002f,-0.0006f,-0.0022f,0.4867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock1) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock2) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock3) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock4) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock5) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator5":{"px":0.1666028719697999,"py":1.7095114471244572,"pz":0.44331865906994034,"ry":215.600292289807,"rx":-21.20756015587108}}}