# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_arm) {transformation: [0.2795f,-0.96f,-0.0188f,-0.2956f,0.0607f,0.0372f,-0.9975f,1.5344f,0.9582f,0.2776f,0.0687f,-0.0431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sweep1) {transformation: [-0.0045f,-0.0004f,0f,-0.5857f,0.0005f,-0.0044f,0f,2.1715f,-0.0003f,-0.0011f,0f,0.4868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_greatsword) {transformation: [-0.003f,-0.0003f,0.0003f,-0.5855f,0.0003f,-0.0029f,0.0007f,2.1735f,-0.0002f,-0.0007f,-0.0029f,0.4867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock1) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock2) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock3) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock4) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock5) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator5":{"px":-0.08879105626464881,"py":1.5735732233430246,"pz":0.6734976780919172,"ry":195.31178543455638,"rx":-85.91481728962232}}}