# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_eyebrow) {transformation: [-0.7708f,-0.0555f,-0.2068f,0.2036f,-0.0666f,0.7965f,0.0348f,1.983f,0.2035f,0.0507f,-0.772f,0.2227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_eye) {transformation: [-0.7727f,0.0095f,-0.2068f,0.2208f,0.003f,0.6394f,0.0348f,1.9327f,0.2071f,0.0262f,-0.772f,0.2152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_eyebrow) {transformation: [-0.7687f,0.0792f,-0.2068f,-0.0266f,0.0727f,0.7959f,0.0348f,1.9836f,0.2092f,0.0146f,-0.772f,0.2844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_eye) {transformation: [-0.7727f,0.0095f,-0.2068f,-0.0342f,0.003f,0.6394f,0.0348f,1.9337f,0.2071f,0.0262f,-0.772f,0.2836f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sweep1) {transformation: [-0.0046f,-0.0004f,0f,-0.5857f,0.0005f,-0.0045f,0f,2.1715f,-0.0003f,-0.0011f,0f,0.4868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_greatsword) {transformation: [-0.0031f,-0.0003f,0.0003f,-0.5855f,0.0003f,-0.003f,0.0007f,2.1735f,-0.0002f,-0.0008f,-0.003f,0.4867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_angry) {transformation: [-0.9397f,-0.342f,0f,0.7813f,-0.342f,0.9397f,0f,2.5313f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock1) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock2) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock3) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock4) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock5) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}