# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_arm) {transformation: [0.1737f,-0.9799f,-0.0978f,-0.2956f,0.6077f,0.1848f,-0.7723f,1.5003f,0.7749f,0.0747f,0.6276f,-0.0431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sweep1) {transformation: [-0.0058f,-0.0005f,0f,-0.5858f,0.0006f,-0.0057f,0f,2.1709f,-0.0004f,-0.0014f,0f,0.4868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_greatsword) {transformation: [-0.0039f,-0.0003f,0.0004f,-0.5855f,0.0004f,-0.0038f,0.0009f,2.1735f,-0.0003f,-0.001f,-0.0038f,0.4867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock1) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock2) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock3) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock4) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock5) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator5":{"px":-0.16834938482874828,"py":1.9496979862076307,"pz":0.5397068044216297,"ry":188.8607019074998,"rx":-50.56437040189402}}}