# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.wither.spawn player @a ~ ~ ~ 1 1
particle minecraft:explosion ~ ~ ~ 0.3 0.3 0.3 0 4