# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_sweep1) {transformation: [-0.0006f,0f,0f,-0.5855f,0.0001f,-0.0005f,0.0001f,2.1732f,0f,-0.0001f,-0.0003f,0.4867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_greatsword) {transformation: [-0.0006f,0f,0.0001f,-0.5855f,0.0001f,-0.0005f,0.0001f,2.1735f,0f,-0.0001f,-0.0005f,0.4867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock1) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock2) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock3) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock4) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock5) {transformation: [0f,0f,0f,-0.875f,0f,0f,0f,2.25f,0f,0f,0f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-0.5855189732901684,"py":2.1729434427847267,"pz":0.4865523538342233,"ry":5.329683702584759,"rx":13.72991038850705}}}