# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:graud_golem/animations/pause_all
tag @s add aj.graud_golem.animation.kurukuru_end.playing
scoreboard players set @s aj.kurukuru_end.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:graud_golem/animations/kurukuru_end/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only