# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pink_skill3_d rig_hash set value 'fd8f55cb0d908459db07a140c29cf68344decf2a1a10f4842ae01d05c6dfc318'
scoreboard objectives add aj.1.frame dummy