# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_star_skill1_2/animations/pause_all
tag @s add aj.pink_star_skill1_2.animation.shoot_r.playing
scoreboard players set @s aj.shoot_r.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:pink_star_skill1_2/animations/shoot_r/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only