# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.nothing.frame matches 61.. run scoreboard players set @s aj.nothing.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.nothing.frame
execute at @s run function animated_java:piglin_girl_head/animations/nothing/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.nothing.frame 1