# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.big_hoglin_head.root] run return 0
execute if entity @s[tag=aj.big_hoglin_head.animation.roar.playing] run function animated_java:big_hoglin_head/animations/roar/zzz/on_tick
execute if entity @s[tag=aj.big_hoglin_head.animation.nothing.playing] run function animated_java:big_hoglin_head/animations/nothing/zzz/on_tick
execute if entity @s[tag=aj.big_hoglin_head.animation.attack.playing] run function animated_java:big_hoglin_head/animations/attack/zzz/on_tick
execute if entity @s[tag=aj.big_hoglin_head.animation.die.playing] run function animated_java:big_hoglin_head/animations/die/zzz/on_tick
execute if entity @s[tag=aj.big_hoglin_head.animation.die_roar.playing] run function animated_java:big_hoglin_head/animations/die_roar/zzz/on_tick
execute on passengers run rotate @s ~ ~