# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.knightsword.root] run return 0
execute if entity @s[tag=aj.knightsword.animation.knight_sword_left_click.playing] run function animated_java:knightsword/animations/knight_sword_left_click/zzz/on_tick
execute if entity @s[tag=aj.knightsword.animation.knight_sword_standby.playing] run function animated_java:knightsword/animations/knight_sword_standby/zzz/on_tick
execute if entity @s[tag=aj.knightsword.animation.using_knight_sword.playing] run function animated_java:knightsword/animations/using_knight_sword/zzz/on_tick
execute if entity @s[tag=aj.knightsword.animation.knight_sword_right_ability.playing] run function animated_java:knightsword/animations/knight_sword_right_ability/zzz/on_tick
execute on passengers run rotate @s ~ ~