# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [-0.8881f,0.325f,-0.325f,0f,0.4596f,0.628f,-0.628f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [-0.809f,0f,-0.5878f,0f,0f,1f,0f,3.0313f,0.5878f,0f,-0.809f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [-0.8881f,-0.325f,-0.325f,0f,-0.4596f,0.628f,0.628f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_4) {transformation: [-0.2809f,-0.9597f,0f,-3.14f,-0.9597f,0.2809f,0f,1.3794f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_3) {transformation: [-0.2809f,-0.9597f,0f,-2.8065f,-0.9597f,0.2809f,0f,2.5191f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_2) {transformation: [-0.9647f,-0.2633f,0f,-1.7212f,-0.2633f,0.9647f,0f,2.8153f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_1) {transformation: [-0.827f,0.5623f,0f,-0.6875f,0.5623f,0.827f,0f,2.1125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg1":{"px":-3.1400330847422016,"py":1.3793920980398056,"pz":-3.845431466446327e-16,"ry":0,"rx":-7.062250076880254e-31}}}