# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '09e8551158208e7f33a81d7a5f675d41192388088c8b61cce84a2edc06f68447'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack