# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp args
$data modify storage animated_java:temp args merge value {command:'$(command)'}
execute at @s on passengers if entity @s[tag=aj.global.data] run function animated_java:pink_star_skill1_3/zzz/at_all_locators/as_data