# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pink_star_skill1_3 rig_hash set value '4e6728c46f2a41c680ed09c47b36672b3bd5cb0c57f46f4f270d174be0658a91'
scoreboard objectives add aj.1.frame dummy