# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:graud_golem/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.graud_golem.node.core] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,0.7071f,-0.7071f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.case] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,3.0313f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,3.0313f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.plate] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.ball] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,0.7071f,0.7071f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg1_4] run data merge entity @s { transformation: [-1f,0f,0f,-4.25f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg1_3] run data merge entity @s { transformation: [-1f,0f,0f,-3.0625f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg1_2] run data merge entity @s { transformation: [-1f,0f,0f,-1.9375f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg1_1] run data merge entity @s { transformation: [-1f,0f,0f,-0.6875f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg2_4] run data merge entity @s { transformation: [-1f,0f,0f,4.25f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg2_3] run data merge entity @s { transformation: [-1f,0f,0f,3.0625f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg2_2] run data merge entity @s { transformation: [-1f,0f,0f,1.9375f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg2_1] run data merge entity @s { transformation: [-1f,0f,0f,0.6875f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg3_4] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,4.25f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg3_3] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,3.0625f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg3_2] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,1.9375f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg3_1] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,0.6875f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg4_4] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,-4.25f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg4_3] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,-3.0625f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg4_2] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,-1.9375f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.leg4_1] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,-0.6875f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.all] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,3.0313f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.graud_golem.node.bone] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }