# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '1479dc402d41c24c524a5e88bf89c6f5d6d19614e15dbc9598f3e0a3e64b01b8'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack