# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:sword_model/animations/pause_all
tag @s add aj.sword_model.animation.run_keep.playing
scoreboard players set @s aj.run_keep.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:sword_model/animations/run_keep/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only