# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.axe_jump_jump_late.frame matches 36.. run scoreboard players set @s aj.axe_jump_jump_late.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.axe_jump_jump_late.frame
execute at @s run function animated_java:piglin_girl/animations/axe_jump_jump_late/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.axe_jump_jump_late.frame 1