# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl_head/animations/nothing/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.nothing.frame 1