# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_sandstorm/animations/sandstorm/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.sandstorm.frame 1