# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body1) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.3042f,0f,0f,-1f,0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.0156f,0f,1f,0f,1.3177f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.5f,0.866f,0f,0.2063f,0.866f,0.5f,0f,1.519f,0f,0f,-1f,-0.025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.5f,-0.866f,0f,-0.2062f,-0.866f,0.5f,0f,1.519f,0f,0f,-1f,-0.025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}