# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:boss_box rig_hash set value '0baf7622c3859fbb5a194c3ab88437f75e8c2140ddc0305915bffd11f0a84793'
scoreboard objectives add aj.open_box.frame dummy