# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pink_star_skill1_2.node.bone] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pink_star_skill1_2.node.bone2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pink_star_skill1_2.node.bone3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pink_star_skill1_2.node.bone4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pink_star_skill1_2.node.bone5] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone5 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.pink_star_skill1_2.node.3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_3 set from storage animated_java:gu out