# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_battle_boss_feet/animations/battle_ranged_walk/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.battle_ranged_walk.frame 1