# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:big_hoglin/animations/die_run2/zzz/apply_frame {frame: 10}
scoreboard players add @s aj.die_run2.frame 1