# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bangs) {transformation: [-1f,0f,0f,0.0023f,0f,0.9365f,-0.3505f,0.438f,0f,-0.3505f,-0.9365f,0.2586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bangs_l) {transformation: [-0.9874f,0.1585f,0f,-0.2138f,0.1585f,0.9874f,0f,0.3178f,0f,0f,-1f,0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bangs_r) {transformation: [-0.9874f,-0.1585f,0f,0.2434f,-0.1585f,0.9874f,0f,0.3178f,0f,0f,-1f,0.2695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_pupil2) {transformation: [0f,0f,0f,-0.039f,0f,0f,0f,0.3719f,0f,0f,0f,0.5243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_pupil) {transformation: [-1.0563f,0f,0f,0.1412f,0f,1f,0f,0.1482f,0f,0f,-1f,0.2622f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_pupil2) {transformation: [0f,0f,0f,-0.0534f,0f,0f,0f,0.3719f,0f,0f,0f,0.5243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_pupil) {transformation: [-1.0563f,0f,0f,-0.1327f,0f,1f,0f,0.1531f,0f,0f,-1f,0.2606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}