# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.right_front] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_front set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.left_front] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_front set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.front] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_front set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.right_behind] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_behind set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.left_behind] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_behind set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.back] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_back set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.tale3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tale3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.tale2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tale2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.rat.node.tale1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tale1 set from storage animated_java:gu out