# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '0a048473cf1288af694b41d18d33dd723fbecb720211f7b28fc9266604d2f954'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack