# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_npc/animations/idle/zzz/apply_frame {frame: 275}
scoreboard players add @s aj.idle.frame 1