# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pink_boss1_head rig_hash set value '5e003968042479415a09676a0ad292c5aec2b8afdde028170f3e33ae3f777cba'
scoreboard objectives add aj.size.frame dummy