# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.battle_melee_4.frame matches 31.. run scoreboard players set @s aj.battle_melee_4.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.battle_melee_4.frame
execute at @s run function animated_java:gray_battle_boss_feet/animations/battle_melee_4/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.battle_melee_4.frame 1