# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:big_hoglin/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '7564bb4cab727292830a3ea6ae50f7d441aa615382ef02b707c224c5ec646846'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack