# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.archdemon.node.left_leg] at @s run function animated_java:archdemon/variants/hurt/zzz/apply_to_node_left_leg
execute on passengers if entity @s[tag=aj.archdemon.node.right_leg] at @s run function animated_java:archdemon/variants/hurt/zzz/apply_to_node_right_leg
execute on passengers if entity @s[tag=aj.archdemon.node.right_hand] at @s run function animated_java:archdemon/variants/hurt/zzz/apply_to_node_right_hand
execute on passengers if entity @s[tag=aj.archdemon.node.left_hand] at @s run function animated_java:archdemon/variants/hurt/zzz/apply_to_node_left_hand
execute on passengers if entity @s[tag=aj.archdemon.node.head] at @s run function animated_java:archdemon/variants/hurt/zzz/apply_to_node_head
execute on passengers if entity @s[tag=aj.archdemon.node.body] at @s run function animated_java:archdemon/variants/hurt/zzz/apply_to_node_body
execute on passengers if entity @s[tag=aj.archdemon.node.right_wing] at @s run function animated_java:archdemon/variants/hurt/zzz/apply_to_node_right_wing
execute on passengers if entity @s[tag=aj.archdemon.node.left_wing] at @s run function animated_java:archdemon/variants/hurt/zzz/apply_to_node_left_wing
return 1