# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:washing_machice/animations/pause_all
tag @s add aj.washing_machice.animation.move.playing
scoreboard players set @s aj.move.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:washing_machice/animations/move/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only