# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.scourge_staff.animation.scourge_staff_left_click.playing
tag @s remove aj.scourge_staff.animation.scourge_staff_standby.playing
tag @s remove aj.scourge_staff.animation.scourge_staff_using_right_click.playing
tag @s remove aj.scourge_staff.animation.scourge_staff_used_right_click.playing