# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pink_star_skill1 rig_hash set value 'f25e5e36c9b9fa53ce3df2158ea317205e3b6135920be6c03231b01d5ec93b03'
scoreboard objectives add aj.4.frame dummy
scoreboard objectives add aj.4_3.frame dummy
scoreboard objectives add aj.3.frame dummy
scoreboard objectives add aj.3_2.frame dummy
scoreboard objectives add aj.2.frame dummy
scoreboard objectives add aj.2_1.frame dummy
scoreboard objectives add aj.1.frame dummy