# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.4.frame
scoreboard objectives remove aj.4_3.frame
scoreboard objectives remove aj.3.frame
scoreboard objectives remove aj.3_2.frame
scoreboard objectives remove aj.2.frame
scoreboard objectives remove aj.2_1.frame
scoreboard objectives remove aj.1.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:pink_star_skill1)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'pink_star_skill1'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']