# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_boss1/animations/pause_all
tag @s add aj.pink_boss1.animation.moeve1.playing
scoreboard players set @s aj.moeve1.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:pink_boss1/animations/moeve1/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only