# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0784f,0f,0f,0f,0f,1.0784f,0f,0.0156f,0f,0f,-1.0784f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0784f,0f,0f,0.2696f,0f,1.0784f,0f,1.431f,0f,0f,-1.0784f,0.5392f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0784f,0f,0f,0f,0f,1.0784f,0f,0.0156f,0f,0f,-1.0784f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.0784f,0f,0f,-0.337f,0f,1.0784f,0f,1.4984f,0f,0f,-1.0784f,0.4044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0784f,0f,0f,0f,0f,0.9774f,0.4558f,0.757f,0f,0.4558f,-0.9774f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0784f,0f,0f,0f,0f,0.9774f,0.4558f,1.4984f,0f,0.4558f,-0.9774f,0.4044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}