# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0648f,0f,0f,0f,0f,1.0648f,0f,0.0156f,0f,0f,-1.0648f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0648f,0f,0f,0.2662f,0f,1.0648f,0f,1.4132f,0f,0f,-1.0648f,0.5324f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0648f,0f,0f,0f,0f,1.0648f,0f,0.0156f,0f,0f,-1.0648f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.0648f,0f,0f,-0.3328f,0f,1.0648f,0f,1.4797f,0f,0f,-1.0648f,0.3993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0648f,0f,0f,0f,0f,0.965f,0.45f,0.7477f,0f,0.45f,-0.965f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0648f,0f,0f,0f,0f,0.965f,0.45f,1.4797f,0f,0.45f,-0.965f,0.3993f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}