# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from entity @s data.locators.interaction1.uuid
function animated_java:gray_coffin/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.interaction2.uuid
function animated_java:gray_coffin/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.interaction3.uuid
function animated_java:gray_coffin/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.hitbox1.uuid
function animated_java:gray_coffin/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.hitbox2.uuid
function animated_java:gray_coffin/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.hitbox3.uuid
function animated_java:gray_coffin/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args