# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add gray.locator
scoreboard players operation @s gray.id = @a[tag=gray.user,limit=1] gray.id
function animated_java:global/util/get_entity_stack_uuids