# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.graud_golem.node.leg2_4] at @s run function animated_java:graud_golem/variants/leg2_damage/zzz/apply_to_node_leg2_4
execute on passengers if entity @s[tag=aj.graud_golem.node.leg2_3] at @s run function animated_java:graud_golem/variants/leg2_damage/zzz/apply_to_node_leg2_3
execute on passengers if entity @s[tag=aj.graud_golem.node.leg2_2] at @s run function animated_java:graud_golem/variants/leg2_damage/zzz/apply_to_node_leg2_2
execute on passengers if entity @s[tag=aj.graud_golem.node.leg2_1] at @s run function animated_java:graud_golem/variants/leg2_damage/zzz/apply_to_node_leg2_1
return 1