# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [-0.1951f,-0.6935f,0.6935f,0f,-0.9808f,0.1379f,-0.1379f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [0f,0f,1f,0f,0f,1f,0f,3.0313f,-1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_plate) {transformation: [0f,0f,-1f,0f,0f,1f,0f,2.5f,1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [-0.1951f,0.6935f,0.6935f,0f,0.9808f,0.1379f,0.1379f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_4) {transformation: [0f,1f,0f,2.2462f,1f,0f,0f,0.1226f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_3) {transformation: [0f,1f,0f,2.2462f,1f,0f,0f,1.3101f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_2) {transformation: [-0.3007f,0.9537f,0f,1.9079f,0.9537f,0.3007f,0f,2.383f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_1) {transformation: [-0.9763f,-0.2164f,0f,0.6875f,-0.2164f,0.9763f,0f,2.1125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_4) {transformation: [-1f,0f,0f,0f,0f,-0.4226f,0.9063f,1.6516f,0f,0.9063f,0.4226f,1.7025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_3) {transformation: [-1f,0f,0f,0f,0f,-0.4226f,0.9063f,2.7278f,0f,0.9063f,0.4226f,2.2044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_2) {transformation: [-1f,0f,0f,0f,0f,0.9063f,0.4226f,3.2033f,0f,0.4226f,-0.9063f,1.1848f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_1) {transformation: [-1f,0f,0f,0f,0f,0.4226f,-0.9063f,2.0704f,0f,-0.9063f,-0.4226f,0.6565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_4) {transformation: [-1f,0f,0f,0f,0f,-0.4061f,-0.9138f,1.4868f,0f,-0.9138f,0.4061f,-1.7325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_3) {transformation: [-1f,0f,0f,0f,0f,-0.4061f,-0.9138f,2.572f,0f,-0.9138f,0.4061f,-2.2147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_2) {transformation: [-1f,0f,0f,0f,0f,0.874f,-0.4859f,3.1187f,0f,-0.4859f,-0.874f,-1.2314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_1) {transformation: [-1f,0f,0f,0f,0f,0.4859f,0.874f,2.0262f,0f,0.874f,-0.4859f,-0.624f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg2":{"px":2.246164033342225,"py":0.12261794783087376,"pz":2.750757593792464e-16,"ry":0,"rx":7.062250076880254e-31},"leg3":{"px":-2.0850018649161109e-16,"py":1.651570412348122,"pz":1.702533225390186,"ry":180,"rx":65.00000000000003},"leg4":{"px":2.1216950661617917e-16,"py":1.4867860965364834,"pz":-1.7324954979990952,"ry":180,"rx":-66.04254400172769}}}