# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [-0.9101f,-0.293f,0.293f,0f,-0.4144f,0.6435f,-0.6435f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [-0.809f,0f,0.5878f,0f,0f,1f,0f,3.0313f,-0.5878f,0f,-0.809f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_plate) {transformation: [-0.809f,0f,-0.5878f,0f,0f,1f,0f,2.5f,0.5878f,0f,-0.809f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [-0.9101f,0.293f,0.293f,0f,0.4144f,0.6435f,0.6435f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_4) {transformation: [-1f,0f,0f,0f,0f,-0.8461f,-0.533f,1.0392f,0f,-0.533f,0.8461f,-1.2747f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_3) {transformation: [-1f,0f,0f,0f,0f,-0.8461f,-0.533f,1.6721f,0f,-0.533f,0.8461f,-2.2795f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_2) {transformation: [-1f,0f,0f,0f,0f,0.4531f,-0.8914f,2.6749f,0f,-0.8914f,-0.4531f,-1.7697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_1) {transformation: [-1f,0f,0f,0f,0f,0.8817f,0.4717f,2.0853f,0f,0.4717f,-0.8817f,-0.6675f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg4":{"px":1.5610455585005327e-16,"py":1.0391900903475007,"pz":-1.274690432855737,"ry":180,"rx":-32.20592592592592}}}