# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [-0.9826f,-0.1314f,0.1314f,0f,-0.1858f,0.6948f,-0.6948f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [-0.9511f,0f,0.309f,0f,0f,1f,0f,3.0313f,-0.309f,0f,-0.9511f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_plate) {transformation: [-0.9511f,0f,-0.309f,0f,0f,1f,0f,2.5f,0.309f,0f,-0.9511f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [-0.9826f,0.1314f,0.1314f,0f,0.1858f,0.6948f,0.6948f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_4) {transformation: [-1f,0f,0f,0f,0f,-0.4665f,-0.8845f,0.3976f,0f,-0.8845f,0.4665f,-1.7182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_3) {transformation: [-1f,0f,0f,0f,0f,-0.4665f,-0.8845f,1.448f,0f,-0.8845f,0.4665f,-2.2723f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_2) {transformation: [-1f,0f,0f,0f,0f,0.3628f,-0.9319f,2.4963f,0f,-0.9319f,-0.3628f,-1.8642f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_1) {transformation: [-1f,0f,0f,0f,0f,0.9485f,0.3168f,2.1003f,0f,0.3168f,-0.9485f,-0.6786f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg4":{"px":2.1042457699778077e-16,"py":0.3976280542277626,"pz":-1.718247066372823,"ry":180,"rx":-62.189629629629614}}}