# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [-0.9963f,-0.0609f,0.0609f,0f,-0.0861f,0.7045f,-0.7045f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [-0.9877f,0f,0.1564f,0f,0f,1f,0f,3.0313f,-0.1564f,0f,-0.9877f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_plate) {transformation: [-0.9877f,0f,-0.1564f,0f,0f,1f,0f,2.5f,0.1564f,0f,-0.9877f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [-0.9963f,0.0609f,0.0609f,0f,0.0861f,0.7045f,0.7045f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_4) {transformation: [-1f,0f,0f,0f,0f,-0.187f,-0.9824f,0.1992f,0f,-0.9824f,0.187f,-2.0388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_3) {transformation: [-1f,0f,0f,0f,0f,-0.187f,-0.9824f,1.3658f,0f,-0.9824f,0.187f,-2.2609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_2) {transformation: [-1f,0f,0f,0f,0f,0.3286f,-0.9445f,2.4283f,0f,-0.9445f,-0.3286f,-1.8912f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_1) {transformation: [-1f,0f,0f,0f,0f,0.9663f,0.2572f,2.1068f,0f,0.2572f,-0.9663f,-0.6833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg4":{"px":2.4967786804962447e-16,"py":0.19924280427946317,"pz":-2.038774512156974,"ry":180,"rx":-79.2209259259259}}}