# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result storage pink:npc_talk sound1 float 0.1 run random value 0..20
execute store result storage pink:npc_talk sound2 float 0.1 run random value 0..20
execute at @n[tag=pink.room] run function pink:npc/room/sound1 with storage pink:npc_talk {}