# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
execute if entity @e[tag=pink.room,tag=!chest] as @e[tag=pink.room,limit=1,sort=random,tag=!chest] at @s run function pink:npc/room/fill
execute if entity @e[tag=pink.room,tag=!chest] as @e[tag=pink.room,limit=1,sort=random,tag=!chest] at @s run function pink:npc/room/fill
execute unless entity @e[tag=pink.room,tag=!chest] as @e[tag=pink.room,limit=1,sort=random,tag=chest] at @s run function pink:npc/room/fill