# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
effect give @a minecraft:slow_falling 1 0 true
tp @a 8 62 -17 0 90
execute as @n[tag=aj.pink_npc] run function animated_java:pink_npc/remove/this
gamemode survival @a