# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle dust{color:[0.290,0.290,0.290],scale:1.5} ~ ~ ~ .3 .3 .3 0 25 normal
particle minecraft:end_rod ~ ~ ~ 0 0 0 0.2 15