# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
execute as @a run spectate @n[tag=pink.camera2] @s
execute positioned as a7-0-0-0-0 run setblock ~8 ~56 ~-17 minecraft:light[level=10]