# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gray_battle_boss_feet.root] run return 0
execute if entity @s[tag=aj.gray_battle_boss_feet.animation.battle_.playing] run function animated_java:gray_battle_boss_feet/animations/battle_/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_feet.animation.battle_spawn.playing] run function animated_java:gray_battle_boss_feet/animations/battle_spawn/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_feet.animation.battle_ranged_walk.playing] run function animated_java:gray_battle_boss_feet/animations/battle_ranged_walk/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_feet.animation.battle_ranged_sword_beam.playing] run function animated_java:gray_battle_boss_feet/animations/battle_ranged_sword_beam/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_feet.animation.battle_melee_walk.playing] run function animated_java:gray_battle_boss_feet/animations/battle_melee_walk/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_feet.animation.battle_melee_2.playing] run function animated_java:gray_battle_boss_feet/animations/battle_melee_2/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_feet.animation.battle_melee_4.playing] run function animated_java:gray_battle_boss_feet/animations/battle_melee_4/zzz/on_tick
execute on passengers run rotate @s ~ ~