# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_star_skill1/animations/pause_all
tag @s add aj.pink_star_skill1.animation.4_3.playing
scoreboard players set @s aj.4_3.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:pink_star_skill1/animations/4_3/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only