# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '4e6728c46f2a41c680ed09c47b36672b3bd5cb0c57f46f4f270d174be0658a91'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack