# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scourge_staff/animations/pause_all
scoreboard players set @s aj.scourge_staff_standby.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:scourge_staff/animations/scourge_staff_standby/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only