# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add light_green.boss.graud_golem.head
function animated_java:global/util/get_entity_stack_uuids