# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
attribute @s minecraft:max_health base set 1024
data modify entity @s Health set value 1024
data modify entity @s Invulnerable set value true
data modify entity @s Silent set value true
data modify entity @s NoAI set value true
effect give @s minecraft:invisibility infinite 0 true
data modify entity @s DeathLootTable set value ""
scoreboard players set @s light_green.mob.ai 3
tag @s add light_green
tag @s add light_green.mob
tag @s add light_green.boss
tag @s add light_green.boss.graud_golem_leg
scoreboard players set @s light_green.leg.health -924
function animated_java:global/util/get_entity_stack_uuids