# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scourge_staff/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.scourge_staff.node.group] run data merge entity @s { transformation: [-1.25f,0f,0f,0f,0f,1.25f,0f,0.5f,0f,0f,-1.25f,0f,0f,0f,0f,1f], start_interpolation: -1 }