# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon minecraft:marker ^0.06313625 ^1.2572075 ^-0.20055875 {Tags:["aj.global.bone.shortsword.child","aj.global.bone.shortsword.child.locator","aj.global.bone.shortsword.decendant","aj.global.bone.shortsword.decendant.locator","aj.global.bone.shortsword.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator","aj.gray_gopr.bone.shortsword.child","aj.gray_gopr.bone.shortsword.child.locator","aj.gray_gopr.bone.shortsword.decendant","aj.gray_gopr.bone.shortsword.decendant.locator","aj.gray_gopr.bone.shortsword.tree","aj.gray_gopr.entity","aj.gray_gopr.locator","aj.gray_gopr.locator.locator","aj.gray_gopr.node","aj.gray_gopr.node.locator","aj.new"]}
execute as @n[ type=minecraft:marker, tag=aj.gray_gopr.locator.locator, tag=aj.new, distance=..3 ] run function animated_java:gray_gopr/zzz/summon/as_data_entity/as_locator/locator
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_locator set from storage animated_java:gu out
data modify entity @s data.locators.locator.uuid set from storage animated_java:gu out
summon minecraft:marker ^0.44569625 ^3.152165625 ^0.086545625 {Tags:["aj.global.bone.greatsword.child","aj.global.bone.greatsword.child.locator","aj.global.bone.greatsword.decendant","aj.global.bone.greatsword.decendant.locator","aj.global.bone.greatsword.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator2","aj.gray_gopr.bone.greatsword.child","aj.gray_gopr.bone.greatsword.child.locator","aj.gray_gopr.bone.greatsword.decendant","aj.gray_gopr.bone.greatsword.decendant.locator","aj.gray_gopr.bone.greatsword.tree","aj.gray_gopr.entity","aj.gray_gopr.locator","aj.gray_gopr.locator.locator2","aj.gray_gopr.node","aj.gray_gopr.node.locator2","aj.new"]}
execute as @n[ type=minecraft:marker, tag=aj.gray_gopr.locator.locator2, tag=aj.new, distance=..5 ] run function animated_java:gray_gopr/zzz/summon/as_data_entity/as_locator/locator2
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_locator2 set from storage animated_java:gu out
data modify entity @s data.locators.locator2.uuid set from storage animated_java:gu out
summon minecraft:marker ^0.44569625 ^1.402165625 ^0.086545625 {Tags:["aj.global.bone.greatsword.child","aj.global.bone.greatsword.child.locator","aj.global.bone.greatsword.decendant","aj.global.bone.greatsword.decendant.locator","aj.global.bone.greatsword.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator3","aj.gray_gopr.bone.greatsword.child","aj.gray_gopr.bone.greatsword.child.locator","aj.gray_gopr.bone.greatsword.decendant","aj.gray_gopr.bone.greatsword.decendant.locator","aj.gray_gopr.bone.greatsword.tree","aj.gray_gopr.entity","aj.gray_gopr.locator","aj.gray_gopr.locator.locator3","aj.gray_gopr.node","aj.gray_gopr.node.locator3","aj.new"]}
execute as @n[ type=minecraft:marker, tag=aj.gray_gopr.locator.locator3, tag=aj.new, distance=..4 ] run function animated_java:gray_gopr/zzz/summon/as_data_entity/as_locator/locator3
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_locator3 set from storage animated_java:gu out
data modify entity @s data.locators.locator3.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_gopr.node.sweep] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_sweep set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_gopr.node.shortsword] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_shortsword set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_gopr.node.sweep1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_sweep1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_gopr.node.greatsword] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_greatsword set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_gopr.node.rock1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rock1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_gopr.node.rock2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rock2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_gopr.node.rock3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rock3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_gopr.node.rock4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rock4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_gopr.node.rock5] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rock5 set from storage animated_java:gu out