# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_eyebrow) {transformation: [-0.7932f,-0.1044f,0f,0.1514f,-0.0965f,0.7328f,0.3061f,1.5457f,-0.04f,0.3035f,-0.7391f,0.608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_eyebrow) {transformation: [-0.7932f,0.1044f,0f,-0.0994f,0.0965f,0.7328f,0.3061f,1.5454f,0.04f,0.3035f,-0.7391f,0.6079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth) {transformation: [-0.8f,0f,0f,0.0156f,0f,0.7391f,0.3061f,1.3312f,0f,0.3061f,-0.7391f,0.5175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_question_mark) {transformation: [0f,0f,0f,-0.5937f,0f,0f,0f,0.3125f,0f,0f,0f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_exclamation_mark) {transformation: [0f,0f,0f,-0.6355f,0f,0f,0f,0.4833f,0f,0f,0f,-0.1915f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_angry) {transformation: [-0.2957f,-0.1539f,0f,0.5938f,-0.1539f,0.2957f,0f,1.9688f,0f,0f,-0.3333f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ellipsis1) {transformation: [0f,0f,0f,-0.6344f,0f,0f,0f,0.0781f,0f,0f,0f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ellipsis2) {transformation: [0f,0f,0f,-0.6344f,0f,0f,0f,0.0781f,0f,0f,0f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ellipsis3) {transformation: [0f,0f,0f,-0.6344f,0f,0f,0f,0.0781f,0f,0f,0f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator3":{"px":0.01309537499999993,"py":1.3166659565092247,"pz":0.5656081222866909,"ry":0,"rx":22.499999999999996}}}