# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:sword_double_model/animations/run_keep/zzz/apply_frame {frame: 15}
scoreboard players add @s aj.run_keep.frame 1