# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute if score @s aj.run_keep.frame matches -1 run function animated_java:sword_double_model/animations/run_keep/zzz/function_keyframe_loop_patch
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.run_keep.frame
function animated_java:sword_double_model/animations/run_keep/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.run_keep.frame matches 14.. run return run scoreboard players set @s aj.run_keep.frame -1
scoreboard players add @s aj.run_keep.frame 1