# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.gray_plot_boss.animation.plot_wake.playing
tag @s remove aj.gray_plot_boss.animation.plot_weak.playing
tag @s remove aj.gray_plot_boss.animation.plot_death.playing