# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gray_battle_boss_body rig_hash set value '521ba35407ea5950cc93e745b0ced5ab2b02fe6362ed7f2737e16a1577bedfa2'
scoreboard objectives add aj.battle_spawn.frame dummy
scoreboard objectives add aj.battle_walk.frame dummy
scoreboard objectives add aj.battle_ranged_sandsword.frame dummy
scoreboard objectives add aj.battle_ranged_greatsword.frame dummy
scoreboard objectives add aj.battle_ranged_sword_beam.frame dummy
scoreboard objectives add aj.battle_melee_2.frame dummy
scoreboard objectives add aj.battle_melee_3.frame dummy
scoreboard objectives add aj.battle_melee_4.frame dummy