# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '6646a4e50247e63c37b186c14e64e33a1fd6fd2265e9338dbbf252ba850f65ab'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack