# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add light_green.piglin_girl.summon_camera1
function animated_java:global/util/get_entity_stack_uuids