# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '186ac40fc54a9df49e0c280bade25e0dcd11b9a29c3bd8f42e8acee4d603b788'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack