# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-1.125 ^0 ^-2.1875 ~0 ~0
data modify entity @s data.cameras.camera2 merge value { px: -1.125, py: 0, pz: -2.1875, ry: 0, rx: 0 }