# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:reverend_sceptre/animations/reverend_sceptre_standby/zzz/apply_frame {frame: 120}
scoreboard players add @s aj.reverend_sceptre_standby.frame 1