# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0168f,0f,0f,0f,0f,1.0168f,0f,0.0156f,0f,0f,-1.0168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0168f,0f,0f,0.2542f,0f,1.0168f,0f,1.4137f,0f,0f,-1.0168f,0.0636f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0168f,0f,0f,0f,0f,1.0168f,0f,0.0156f,0f,0f,-1.0168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-0.9822f,0.2632f,0f,-0.3177f,-0.2609f,-0.9738f,-0.1327f,1.4773f,-0.0344f,-0.1282f,1.0081f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0168f,0f,0f,0f,0f,1.0168f,0f,0.7147f,0f,0f,-1.0168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0168f,0f,0f,0f,0f,1.0168f,0f,1.4773f,0f,0f,-1.0168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,-0.75f,0f,1f,0f,2.941f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1f,0f,0f,-0.4375f,0f,1f,0f,2.9965f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1f,0f,0f,-1.0625f,0f,1f,0f,2.9965f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}