# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0168f,0f,0f,0f,0f,1.0168f,0f,0.0156f,0f,0f,-1.0168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0168f,0f,0f,0.2542f,0f,1.0168f,0f,1.4137f,0f,0f,-1.0168f,0.0636f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0168f,0f,0f,0f,0f,1.0168f,0f,0.0156f,0f,0f,-1.0168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.016f,-0.0337f,0.0224f,-0.3177f,-0.0401f,0.9113f,-0.4493f,1.4773f,-0.0052f,-0.4498f,-0.9119f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0168f,0f,0f,0f,0f,1.0168f,0f,0.7147f,0f,0f,-1.0168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0168f,0f,0f,0f,0f,1.0168f,0f,1.4773f,0f,0f,-1.0168f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-0.152f,0f,0f,-0.5592f,0f,0.152f,0f,1.4932f,0f,0f,-0.152f,-0.6329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-0.152f,0f,0f,-0.5117f,0f,0.152f,0f,1.4975f,0f,0f,-0.152f,-0.6329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-0.152f,0f,0f,-0.6067f,0f,0.152f,0f,1.4975f,0f,0f,-0.152f,-0.6329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}