# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0424f,0f,0f,0f,0f,1.0424f,0f,0.0156f,0f,0f,-1.0424f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0424f,0f,0f,0.2606f,0f,1.0424f,0f,1.4489f,0f,0f,-1.0424f,0.0652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0424f,0f,0f,0f,0f,1.0424f,0f,0.0156f,0f,0f,-1.0424f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.0374f,-0.0311f,0.0976f,-0.3257f,-0.1016f,0.4403f,-0.9393f,1.5141f,-0.0132f,-0.9443f,-0.4412f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0424f,0f,0f,0f,0f,1.0424f,0f,0.7323f,0f,0f,-1.0424f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0424f,0f,0f,0f,0f,1.0424f,0f,1.5141f,0f,0f,-1.0424f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-0.376f,0f,0f,-0.6096f,0f,0.376f,0f,1.9136f,0f,0f,-0.376f,-0.4327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-0.376f,0f,0f,-0.4921f,0f,0.376f,0f,1.8555f,0f,0f,-0.376f,-0.4327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-0.376f,0f,0f,-0.7271f,0f,0.376f,0f,1.8555f,0f,0f,-0.376f,-0.4327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}