# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0696f,0f,0f,0f,0f,1.0696f,0f,0.0156f,0f,0f,-1.0696f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0696f,0f,0f,0.2674f,0f,1.0696f,0f,1.4863f,0f,0f,-1.0696f,0.0669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0696f,0f,0f,0f,0f,1.0696f,0f,0.0156f,0f,0f,-1.0696f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.0554f,0.0739f,0.1575f,-0.3343f,-0.1725f,-0.3192f,-1.0062f,1.5532f,-0.0226f,-1.0182f,0.3269f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0696f,0f,0f,0f,0f,1.0696f,0f,0.751f,0f,0f,-1.0696f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0696f,0f,0f,0f,0f,1.0696f,0f,1.5532f,0f,0f,-1.0696f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-0.624f,0f,0f,-0.6654f,0f,0.624f,0f,2.3618f,0f,0f,-0.624f,-0.2111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-0.624f,0f,0f,-0.4704f,0f,0.624f,0f,2.2691f,0f,0f,-0.624f,-0.211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-0.624f,0f,0f,-0.8604f,0f,0.624f,0f,2.2691f,0f,0f,-0.624f,-0.2111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}