# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0912f,0f,0f,0f,0f,1.0912f,0f,0.0156f,0f,0f,-1.0912f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0912f,0f,0f,0.2728f,0f,1.0912f,0f,1.516f,0f,0f,-1.0912f,0.0682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0912f,0f,0f,0f,0f,1.0912f,0f,0.0156f,0f,0f,-1.0912f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.0644f,0.2156f,0.1061f,-0.341f,-0.2382f,-0.8841f,-0.5935f,1.5842f,-0.0313f,-0.6021f,0.9095f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0912f,0f,0f,0f,0f,1.0912f,0f,0.7658f,0f,0f,-1.0912f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0912f,0f,0f,0f,0f,1.0912f,0f,1.5842f,0f,0f,-1.0912f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-0.848f,0f,0f,-0.7158f,0f,0.848f,0f,2.6811f,0f,0f,-0.848f,-0.0108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-0.848f,0f,0f,-0.4508f,0f,0.848f,0f,2.7282f,0f,0f,-0.848f,-0.0108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-0.848f,0f,0f,-0.9808f,0f,0.848f,0f,2.7282f,0f,0f,-0.848f,-0.0108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}