# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^1.5 ^0 ^1 ~0 ~0
data modify entity @s data.locators.camara1 merge value { px: 1.5, py: 0, pz: 1, ry: 0, rx: 0 }