# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^-1.0625 ^2.1875 ^3 ~0 ~0
data modify entity @s data.locators.camara2 merge value { px: -1.0625, py: 2.1875, pz: 3, ry: 0, rx: 0 }