# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0976f,0f,0f,0f,0f,1.0977f,0f,0.0156f,0f,0f,-1.0976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0976f,0f,0f,0.2744f,0f,1.0977f,0f,1.5249f,0f,0f,-1.0976f,0.0686f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0976f,0f,0f,0f,0f,1.0977f,0f,0.0156f,0f,0f,-1.0976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.0602f,0.2841f,0f,-0.343f,-0.2817f,-1.0512f,-0.1433f,1.5935f,-0.0371f,-0.1384f,1.0883f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0976f,0f,0f,0f,0f,1.0977f,0f,0.7703f,0f,0f,-1.0976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0976f,0f,0f,0f,0f,1.0977f,0f,1.5935f,0f,0f,-1.0976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1.5f,0f,0f,-0.0625f,0f,1.5f,0f,0.7793f,0f,0f,-1.5f,0.7963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1.5f,0f,0f,1.0903f,0f,1.5f,0f,1.002f,0f,0f,-1.5f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1.5f,0f,0f,-0.8732f,0f,1.5f,0f,1.002f,0f,0f,-1.5f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}