# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0815f,0f,0f,0f,0f,1.0816f,0f,0.0156f,0f,0f,-1.0815f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0815f,0f,0f,0.2704f,0f,1.0816f,0f,1.5028f,0f,0f,-1.0815f,0.0676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0815f,0f,0f,0f,0f,1.0816f,0f,0.0156f,0f,0f,-1.0815f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.0447f,0.2799f,0f,-0.338f,-0.2775f,-1.0358f,-0.1412f,1.5704f,-0.0365f,-0.1364f,1.0723f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0815f,0f,0f,0f,0f,1.0816f,0f,0.7592f,0f,0f,-1.0815f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0815f,0f,0f,0f,0f,1.0816f,0f,1.5704f,0f,0f,-1.0815f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1.5f,0f,0f,-0.0625f,0f,1.5f,0f,0.9323f,0f,0f,-1.5f,0.7025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1.5f,0f,0f,0.7242f,0f,1.5f,0f,0.849f,0f,0f,-1.5f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1.5f,0f,0f,-0.6902f,0f,1.5f,0f,0.849f,0f,0f,-1.5f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}