# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0068f,0f,0f,0f,0f,1.0069f,0f,0.0156f,0f,0f,-1.0068f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0068f,0f,0f,0.2517f,0f,1.0069f,0f,1.4f,0f,0f,-1.0068f,0.0629f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0068f,0f,0f,0f,0f,1.0069f,0f,0.0156f,0f,0f,-1.0068f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-0.9725f,0.2606f,0f,-0.3146f,-0.2584f,-0.9642f,-0.1314f,1.463f,-0.034f,-0.1269f,0.9982f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0068f,0f,0f,0f,0f,1.0069f,0f,0.7078f,0f,0f,-1.0068f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0068f,0f,0f,0f,0f,1.0069f,0f,1.463f,0f,0f,-1.0068f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1.5f,0f,0f,-0.0625f,0f,1.5f,0f,0.7793f,0f,0f,-1.5f,0.5353f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1.5f,0f,0f,0.3943f,0f,1.5f,0f,1.002f,0f,0f,-1.5f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1.5f,0f,0f,-0.5252f,0f,1.5f,0f,1.002f,0f,0f,-1.5f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}