# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0156f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,1.3906f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0156f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-0.9659f,0.2588f,0f,-0.3125f,-0.2566f,-0.9577f,-0.1305f,1.4531f,-0.0338f,-0.1261f,0.9914f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7031f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4531f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1.5f,0f,0f,-0.0625f,0f,1.5f,0f,0.75f,0f,0f,-1.5f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1.5f,0f,0f,0.4063f,0f,1.5f,0f,1.0313f,0f,0f,-1.5f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1.5f,0f,0f,-0.5312f,0f,1.5f,0f,1.0313f,0f,0f,-1.5f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}