# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0289f,0f,0f,0f,0f,1.029f,0f,0.0156f,0f,0f,-1.0289f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0289f,0f,0f,0.2572f,0f,1.029f,0f,1.4304f,0f,0f,-1.0289f,0.0643f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0289f,0f,0f,0f,0f,1.029f,0f,0.0156f,0f,0f,-1.0289f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.0266f,-0.0428f,0.0547f,-0.3215f,-0.0689f,0.7318f,-0.7201f,1.4947f,-0.009f,-0.7221f,-0.733f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0289f,0f,0f,0f,0f,1.029f,0f,0.723f,0f,0f,-1.0289f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0289f,0f,0f,0f,0f,1.029f,0f,1.4947f,0f,0f,-1.0289f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-0.387f,0f,0f,0.0117f,0f,0.387f,0f,0.3228f,0f,0f,-0.387f,-0.5504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-0.387f,0f,0f,0.1187f,0f,0.387f,0f,0.2944f,0f,0f,-0.387f,-0.5382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-0.387f,0f,0f,-0.1023f,0f,0.387f,0f,0.2944f,0f,0f,-0.387f,-0.5382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}