# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_foot) {transformation: [-1.0976f,0f,0f,0f,0f,1.0977f,0f,0.0156f,0f,0f,-1.0976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.0976f,0f,0f,0.2744f,0f,1.0977f,0f,1.5249f,0f,0f,-1.0976f,0.0686f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_foot) {transformation: [-1.0976f,0f,0f,0f,0f,1.0977f,0f,0.0156f,0f,0f,-1.0976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.0649f,0.2614f,0.051f,-0.343f,-0.264f,-1.0089f,-0.3425f,1.5935f,-0.0347f,-0.3445f,1.0416f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0976f,0f,0f,0f,0f,1.0977f,0f,0.7703f,0f,0f,-1.0976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.0976f,0f,0f,0f,0f,1.0977f,0f,1.5935f,0f,0f,-1.0976f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1.404f,0f,0f,-0.0561f,0f,1.404f,0f,0.7362f,0f,0f,-1.404f,0.5999f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1.404f,0f,0f,1.0229f,0f,1.404f,0f,0.9447f,0f,0f,-1.404f,0.0678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1.404f,0f,0f,-0.815f,0f,1.404f,0f,0.9447f,0f,0f,-1.404f,0.0678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}