# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:scourge_staff/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'a5cf0119f45bee73aeb7cc33c13ceb6fdb3869440b5a0929ede0cf52de26bc53'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack