# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone8) {transformation: [-0.0873f,0f,-0.2106f,0f,0f,1.5f,0f,1.9531f,0.2106f,0f,-0.0873f,-0.7969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone7) {transformation: [-0.2106f,0f,-0.0873f,0.7367f,0f,1.5f,0f,1.7656f,0.0873f,0f,-0.2106f,-0.0225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone12) {transformation: [0.0426f,0f,0.4869f,0.023f,0f,1.3f,0f,2.2969f,-0.4869f,0f,0.0426f,0.3337f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone13) {transformation: [0f,0f,0f,0.3372f,0f,1.3f,0f,1.8906f,0f,0f,0f,-0.0209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone14) {transformation: [0.9778f,0f,-0.509f,0.3085f,0f,1.3f,0f,2.1344f,0.509f,0f,0.9778f,0.1585f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone15) {transformation: [0f,0f,0f,-0.3274f,0f,1.3f,0f,2.1344f,0f,0f,0f,-0.2373f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone16) {transformation: [0f,0f,0f,-0.2095f,0f,1.3f,0f,1.9719f,0f,0f,0f,0.407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [0.0707f,0f,0.8081f,-0.0419f,0f,1.3f,0f,2.2969f,-0.8081f,0f,0.0707f,-0.4126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone18) {transformation: [0.3744f,0f,0.3142f,-0.3556f,0f,1.3f,0f,2.1344f,-0.3142f,0f,0.3744f,0.1754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone19) {transformation: [0f,0f,0f,0.1619f,0f,1.3f,0f,3.1094f,0f,0f,0f,-0.3064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone21) {transformation: [1.2f,0f,0f,-0.4379f,0f,1.1232f,0f,0.0702f,0f,0f,1.2f,0.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone23) {transformation: [1.14f,0f,0f,-0.4223f,0f,1.067f,0f,0.0667f,0f,0f,1.14f,0.172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone22) {transformation: [-1.14f,0f,0f,-0.125f,0f,1.067f,0f,0f,0f,0f,-1.14f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.2f,0f,0f,-0.125f,0f,1.1232f,0f,0f,0f,0f,-1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}