# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone14) {transformation: [0.1753f,0f,-0.0912f,0.3085f,0f,1.3f,0f,2.1344f,0.0912f,0f,0.1753f,0.1585f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone17) {transformation: [0f,0f,0f,-0.0419f,0f,1.3f,0f,2.2969f,0f,0f,0f,-0.4126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone21) {transformation: [1.2f,0f,0f,-0.4379f,0f,0f,0f,0f,0f,0f,1.2f,0.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone23) {transformation: [1.14f,0f,0f,-0.4223f,0f,0f,0f,0f,0f,0f,1.14f,0.172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone22) {transformation: [-1.14f,0f,0f,-0.125f,0f,0f,0f,0f,0f,0f,-1.14f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone20) {transformation: [-1.2f,0f,0f,-0.125f,0f,0f,0f,0f,0f,0f,-1.2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] positioned ^0.0625 ^1.0625 ^0 rotated ~0 ~0 run function animated_java:pink_black2/animations/1/zzz/frames/13_locator_locator