# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone) {transformation: [-1.4142f,-1f,-1f,0f,0f,1.4142f,-1.4142f,2f,1.4142f,-1f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-2.0325f,0f,0.8419f,0f,-0.3222f,1.8478f,-0.7778f,2.0313f,-0.7778f,-0.7654f,-1.8778f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-2.1213f,0f,2.1213f,0f,0.8118f,1.8478f,0.8118f,2.0313f,-1.9598f,0.7654f,-1.9598f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.9375f,0f,0f,0f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone5) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}