# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone) {transformation: [0.1775f,0.0147f,0.0147f,0f,0f,-0.1263f,0.1263f,1.8958f,-0.0207f,0.1255f,0.1255f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [0f,0.1665f,0f,0f,0f,0.2827f,0f,1.901f,0f,-0.0591f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [0f,0.0201f,0f,0f,0f,0.332f,0f,1.901f,0f,0.0215f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-1.5455f,0.6794f,0f,0f,0.4141f,2.5356f,0f,1.9375f,0f,0f,-1.6f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [0f,0f,0f,0f,0f,0f,0f,1.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}