# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone) {transformation: [8.8454f,0.7993f,-13.3086f,0.0779f,7.054f,-13.8333f,3.8575f,1.7773f,-11.3137f,-8f,-8f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [0f,0.3557f,0f,0.0974f,0f,-1.8857f,0f,1.7528f,0f,0.5636f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [0f,1.2626f,0f,0.0974f,0f,-1.5412f,0f,1.7528f,0f,0.1748f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone6) {transformation: [-3.677f,0f,3.677f,0f,0f,5.2f,0f,1.1875f,-3.677f,0f,-3.677f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone5) {transformation: [-4f,0f,0f,0f,0f,4f,0f,1.9375f,0f,0f,-4f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}