# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gray_plot_boss rig_hash set value 'd589f8b03a5c8fadf65cf01468a7d63edc7ab81a35638a14d0a698622e0529dc'
scoreboard objectives add aj.plot_wake.frame dummy
scoreboard objectives add aj.plot_weak.frame dummy
scoreboard objectives add aj.plot_death.frame dummy