# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1667f,0f,1.375f,0f,0f,-1.1667f,0.106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.0586f,0.4106f,1.375f,0f,0.4106f,-1.0586f,-0.106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5095f,0f,0f,0f,-0.106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-0.9909f,0f,0.8922f,-1f,0f,1.3333f,0f,2.947f,-0.8922f,0f,-0.9909f,-0.106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3042f,0f,0.2772f,0.947f,0f,1.3333f,0f,3f,-0.2772f,0f,-1.3042f,0.159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,-0.0133f,0f,1.1388f,0.1269f,3.25f,0f,0.1269f,-1.1388f,0.053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0567f,0f,0.2385f,0f,0f,1.0833f,0f,2f,-0.2385f,0f,-1.0567f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0625f,0f,0f,-0.1954f,0f,2.0625f,0f,3.1271f,0f,0f,-2.0625f,-0.9285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.1104f,0f,0f,0.3576f,0f,2.1104f,0f,3.1271f,0f,0f,-2.1104f,-0.8215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-0.013250000000000085,"py":3.3049962344900505,"pz":0.6880003261352827,"ry":0,"rx":6.359999999999999}}}