# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1667f,0f,1.375f,0f,0f,-1.1667f,0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.135f,0.0317f,1.375f,0f,0.0317f,-1.135f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5585f,0f,0f,0f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3277f,0f,0.122f,-1f,0f,1.3333f,0f,2.996f,-0.122f,0f,-1.3277f,-0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3329f,0f,0.0349f,0.996f,0f,1.3333f,0f,3f,-0.0349f,0f,-1.3329f,0.012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,-0.001f,0f,1.1458f,0.0096f,3.25f,0f,0.0096f,-1.1458f,0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0832f,0f,0.0182f,0f,0f,1.0833f,0f,2f,-0.0182f,0f,-1.0832f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0625f,0f,0f,-0.2459f,0f,2.0625f,0f,3.1252f,0f,0f,-2.0625f,-0.879f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.1104f,0f,0f,0.2581f,0f,2.1104f,0f,3.1252f,0f,0f,-2.1104f,-0.871f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-0.001000000000000078,"py":3.3697596870255784,"pz":0.6300252529758967,"ry":0,"rx":0.4800000000000004}}}