# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pink_black2.root] run return 0
execute if entity @s[tag=aj.pink_black2.animation.1.playing] run function animated_java:pink_black2/animations/1/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:pink_black2/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~