# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.spear_2_run1.frame matches 11.. run scoreboard players set @s aj.spear_2_run1.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.spear_2_run1.frame
execute at @s run function animated_java:piglin_girl/animations/spear_2_run1/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.spear_2_run1.frame 1