# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.to_level2.frame matches 211.. run scoreboard players set @s aj.to_level2.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.to_level2.frame
execute at @s run function animated_java:piglin_girl/animations/to_level2/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.to_level2.frame 1