# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:calamity_treant/animations/calamity_treant_standby/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.calamity_treant_standby.frame 1