# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pink_boss1 rig_hash set value 'beb0680966dd5a57255c7a7a3dae946ad583ac05fd572d26128f4a1f27a694b5'
scoreboard objectives add aj.pose1.frame dummy
scoreboard objectives add aj.size.frame dummy
scoreboard objectives add aj.moeve1.frame dummy