# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_guide/animations/pause_all
tag @s add aj.gray_guide.animation.shake.playing
scoreboard players set @s aj.shake.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:gray_guide/animations/shake/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only