# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_plot_boss/animations/pause_all
scoreboard players set @s aj.plot_wake.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:gray_plot_boss/animations/plot_wake/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only