# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:archdemon/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'bbccc3ff37231dd314ba9fb4b83146e201e0ee6187d55c2301e36b9a44b49305'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack