# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_waterball/animations/shake/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.shake.frame 1