# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.die_roar.frame matches 36.. run scoreboard players set @s aj.die_roar.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.die_roar.frame
execute at @s run function animated_java:big_hoglin_head/animations/die_roar/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.die_roar.frame 1