# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:big_hoglin_head/animations/pause_all
tag @s add aj.big_hoglin_head.animation.die_roar.playing
scoreboard players set @s aj.die_roar.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:big_hoglin_head/animations/die_roar/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only