# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_coffin/zzz/summon/locators_on_summon/zzz/0 with entity @s data.locators.interaction1
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:gray_coffin/zzz/summon/locators_on_summon/zzz/1 with entity @s data.locators.interaction2
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:gray_coffin/zzz/summon/locators_on_summon/zzz/2 with entity @s data.locators.interaction3
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:gray_coffin/zzz/summon/locators_on_summon/zzz/3 with entity @s data.locators.hitbox1
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:gray_coffin/zzz/summon/locators_on_summon/zzz/4 with entity @s data.locators.hitbox2
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:gray_coffin/zzz/summon/locators_on_summon/zzz/5 with entity @s data.locators.hitbox3
data modify entity @s data.uuids append from storage animated_java:temp uuids