# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_magic) {transformation: [-5f,0f,0f,0f,0f,5f,0f,0.0313f,0f,0f,-5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-5f,0f,0f,-1.5625f,0f,5f,0f,-1.9375f,0f,0f,-5f,1.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-5f,0f,0f,1.5625f,0f,5f,0f,-0.375f,0f,0f,-5f,0.9375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-5f,0f,0f,-1.5625f,0f,5f,0f,-0.6875f,0f,0f,-5f,-1.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone3) {transformation: [-5f,0f,0f,1.5625f,0f,5f,0f,-1.625f,0f,0f,-5f,-2.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}