# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idle.frame
scoreboard objectives remove aj.attack1.frame
scoreboard objectives remove aj.attack2.frame
scoreboard objectives remove aj.hurt.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:light_gray_wool_boss)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'light_gray_wool_boss'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']