# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.big_hoglin_head.node.jaw_dirt] at @s run function animated_java:big_hoglin_head/variants/hurt/zzz/apply_to_node_jaw_dirt
execute on passengers if entity @s[tag=aj.big_hoglin_head.node.jaw] at @s run function animated_java:big_hoglin_head/variants/hurt/zzz/apply_to_node_jaw
execute on passengers if entity @s[tag=aj.big_hoglin_head.node.dirt] at @s run function animated_java:big_hoglin_head/variants/hurt/zzz/apply_to_node_dirt
execute on passengers if entity @s[tag=aj.big_hoglin_head.node.r_ear] at @s run function animated_java:big_hoglin_head/variants/hurt/zzz/apply_to_node_r_ear
execute on passengers if entity @s[tag=aj.big_hoglin_head.node.l_ear] at @s run function animated_java:big_hoglin_head/variants/hurt/zzz/apply_to_node_l_ear
execute on passengers if entity @s[tag=aj.big_hoglin_head.node.head] at @s run function animated_java:big_hoglin_head/variants/hurt/zzz/apply_to_node_head
return 1