# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl/animations/pause_all
tag @s add aj.piglin_girl.animation.dagger_run_throw1.playing
scoreboard players set @s aj.dagger_run_throw1.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:piglin_girl/animations/dagger_run_throw1/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only