# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_sweep) {transformation: [-1f,0f,0f,-0.6244f,0f,0f,0f,-0.1909f,0f,0f,0f,-0.1113f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shortsword) {transformation: [-1f,0f,0f,-0.6875f,0f,0.9239f,0.3827f,-0.3373f,0f,0.3827f,-0.9239f,0.0816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_sweep1) {transformation: [0f,0f,0f,0.4375f,0f,0f,0f,0.125f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_greatsword) {transformation: [0f,0f,0f,0.4375f,0f,0f,0f,0.125f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock1) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.1875f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock2) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.1875f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock3) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.1875f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock4) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.1875f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rock5) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.1875f,0f,0f,0f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-0.62436375,"py":0.3974784869924115,"pz":0.35114128226717506,"ry":0,"rx":22.500000000000014},"locator2":{"px":0.4375000819625,"py":0.12503027165625,"pz":0.06250024045625005,"ry":0,"rx":0},"locator3":{"px":0.4375000819625,"py":0.12501277165625,"pz":0.06250024045625005,"ry":0,"rx":0}}}