# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '575a8c5a0a7dfa61b13953c91c4e041a12f9ef13e928c7823ba9c4a04b0d2c23'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack