# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_battle_boss_body/animations/pause_all
tag @s add aj.gray_battle_boss_body.animation.battle_ranged_sword_beam.playing
scoreboard players set @s aj.battle_ranged_sword_beam.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:gray_battle_boss_body/animations/battle_ranged_sword_beam/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only