# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_case) {transformation: [0f,0f,1f,0f,0f,1f,0f,3.0313f,-1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_plate) {transformation: [0f,0f,-1f,0f,0f,1f,0f,2.5f,1f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_4) {transformation: [0f,-1f,0f,-2.2462f,-1f,0f,0f,0.1226f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_3) {transformation: [0f,-1f,0f,-2.2462f,-1f,0f,0f,1.3101f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_2) {transformation: [-0.3007f,-0.9537f,0f,-1.9079f,-0.9537f,0.3007f,0f,2.383f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg1_1) {transformation: [-0.9763f,0.2164f,0f,-0.6875f,0.2164f,0.9763f,0f,2.1125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_4) {transformation: [-0.0674f,0.9977f,0f,2.0416f,0.9977f,0.0674f,0f,0.2243f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_3) {transformation: [-0.0674f,0.9977f,0f,1.9616f,0.9977f,0.0674f,0f,1.4091f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_2) {transformation: [0.0226f,0.9997f,0f,1.9871f,0.9997f,-0.0226f,0f,2.5338f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_1) {transformation: [0.1895f,0.9819f,0f,2.224f,0.9819f,-0.1895f,0f,3.7611f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_4) {transformation: [-1f,0f,0f,0f,0f,0f,1f,0.125f,0f,1f,0f,2.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_3) {transformation: [-1f,0f,0f,0f,0f,0f,1f,1.3125f,0f,1f,0f,2.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_2) {transformation: [-1f,0f,0f,0f,0f,0f,1f,2.4375f,0f,1f,0f,2.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_1) {transformation: [-1f,0f,0f,0f,0f,0f,1f,3.6875f,0f,1f,0f,2.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg1":{"px":-2.246164033342225,"py":0.12261794783087376,"pz":2.750757593792464e-16,"ry":360,"rx":7.062250076880254e-31},"leg2":{"px":2.0416163709261252,"py":0.22425464049368715,"pz":-2.500258953741514e-16,"ry":360,"rx":7.062250076880254e-31},"leg3":{"px":2.678914873134837e-16,"py":0.125,"pz":2.1875000000000013,"ry":360,"rx":90}}}