# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_case) {transformation: [-0.309f,0f,0.9511f,0f,0f,1f,0f,3.0313f,-0.9511f,0f,-0.309f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_plate) {transformation: [-0.309f,0f,-0.9511f,0f,0f,1f,0f,2.5f,0.9511f,0f,-0.309f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_4) {transformation: [-0.0205f,0.9998f,0f,2.0372f,0.9998f,0.0205f,0f,0.1787f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_3) {transformation: [-0.0205f,0.9998f,0f,2.0128f,0.9998f,0.0205f,0f,1.366f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_2) {transformation: [0.0195f,0.9998f,0f,2.0348f,0.9998f,-0.0195f,0f,2.4908f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_1) {transformation: [0.1392f,0.9903f,0f,2.2088f,0.9903f,-0.1392f,0f,3.7286f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_4) {transformation: [-1f,0f,0f,0f,0f,0.0684f,0.9977f,0.205f,0f,0.9977f,-0.0684f,2.4889f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_3) {transformation: [-1f,0f,0f,0f,0f,0.0684f,0.9977f,1.3897f,0f,0.9977f,-0.0684f,2.4077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_2) {transformation: [-1f,0f,0f,0f,0f,0.1146f,0.9934f,2.5073f,0f,0.9934f,-0.1146f,2.2788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_1) {transformation: [-1f,0f,0f,0f,0f,0.6231f,0.7822f,3.485f,0f,0.7822f,-0.6231f,1.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg2":{"px":2.0372255799707726,"py":0.17873037917669432,"pz":-2.4948817856523164e-16,"ry":360,"rx":0},"leg3":{"px":3.048050310367472e-16,"py":0.20497204432758442,"pz":2.488921958959631,"ry":360,"rx":86.08}}}