# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_case) {transformation: [-0.454f,0f,0.891f,0f,0f,1f,0f,3.0313f,-0.891f,0f,-0.454f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_plate) {transformation: [-0.454f,0f,-0.891f,0f,0f,1f,0f,2.5f,0.891f,0f,-0.454f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_4) {transformation: [-0.0047f,1f,0f,2.0626f,1f,0.0047f,0f,0.158f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_3) {transformation: [-0.0047f,1f,0f,2.057f,1f,0.0047f,0f,1.3455f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_2) {transformation: [0.0153f,0.9999f,0f,2.0742f,0.9999f,-0.0153f,0f,2.4704f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_1) {transformation: [0.1015f,0.9948f,0f,2.2011f,0.9948f,-0.1015f,0f,3.7139f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_4) {transformation: [-1f,0f,0f,0f,0f,0.0555f,0.9985f,0.2547f,0f,0.9985f,-0.0555f,2.4615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_3) {transformation: [-1f,0f,0f,0f,0f,0.0555f,0.9985f,1.4404f,0f,0.9985f,-0.0555f,2.3956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_2) {transformation: [-1f,0f,0f,0f,0f,0.1894f,0.9819f,2.545f,0f,0.9819f,-0.1894f,2.1825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_1) {transformation: [-1f,0f,0f,0f,0f,0.8985f,0.439f,3.0938f,0f,0.439f,-0.8985f,1.0594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg2":{"px":2.0625983285024048,"py":0.1580290218070135,"pz":-2.525954440927151e-16,"ry":360,"rx":7.062250076880254e-31},"leg3":{"px":3.0144397719601757e-16,"py":0.2547011533449124,"pz":2.461476871583665,"ry":360,"rx":86.82000000000004}}}