# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_case) {transformation: [-0.5878f,0f,0.809f,0f,0f,1f,0f,3.0313f,-0.809f,0f,-0.5878f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_plate) {transformation: [-0.5878f,0f,-0.809f,0f,0f,1f,0f,2.5f,0.809f,0f,-0.5878f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_4) {transformation: [0.0029f,1f,0f,2.1114f,1f,-0.0029f,0f,0.1397f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_3) {transformation: [0.0029f,1f,0f,2.1149f,1f,-0.0029f,0f,1.3272f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_2) {transformation: [0.0089f,1f,0f,2.1249f,1f,-0.0089f,0f,2.4521f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_1) {transformation: [0.0552f,0.9985f,0f,2.1938f,0.9985f,-0.0552f,0f,3.7002f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_4) {transformation: [-1f,0f,0f,0f,0f,0.0305f,0.9995f,0.224f,0f,0.9995f,-0.0305f,2.3738f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_3) {transformation: [-1f,0f,0f,0f,0f,0.0305f,0.9995f,1.411f,0f,0.9995f,-0.0305f,2.3376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_2) {transformation: [-1f,0f,0f,0f,0f,0.2561f,0.9666f,2.4985f,0f,0.9666f,-0.2561f,2.0494f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_1) {transformation: [-1f,0f,0f,0f,0f,0.9986f,0.0537f,2.5656f,0f,0.0537f,-0.9986f,0.8013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg2":{"px":2.1114494943151523,"py":0.13969787348844975,"pz":-2.585779864774349e-16,"ry":360,"rx":7.062250076880254e-31},"leg3":{"px":2.9071211806935445e-16,"py":0.2240406220678295,"pz":2.3738445915325097,"ry":360,"rx":88.25000000000013}}}