# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_case) {transformation: [-0.7071f,0f,0.7071f,0f,0f,1f,0f,3.0313f,-0.7071f,0f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_plate) {transformation: [-0.7071f,0f,-0.7071f,0f,0f,1f,0f,2.5f,0.7071f,0f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_4) {transformation: [0f,1f,0f,2.1875f,1f,0f,0f,0.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_3) {transformation: [0f,1f,0f,2.1875f,1f,0f,0f,1.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_2) {transformation: [0f,1f,0f,2.1875f,1f,0f,0f,2.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg2_1) {transformation: [0f,1f,0f,2.1875f,1f,0f,0f,3.6875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_4) {transformation: [-1f,0f,0f,0f,0f,0f,1f,0.1226f,0f,1f,0f,2.2462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_3) {transformation: [-1f,0f,0f,0f,0f,0f,1f,1.3101f,0f,1f,0f,2.2462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_2) {transformation: [-1f,0f,0f,0f,0f,0.3007f,0.9537f,2.383f,0f,0.9537f,-0.3007f,1.9079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_1) {transformation: [-1f,0f,0f,0f,0f,0.9763f,-0.2164f,2.1125f,0f,-0.2164f,-0.9763f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg2":{"px":2.1875000000000013,"py":0.125,"pz":-2.678914873134837e-16,"ry":360,"rx":0},"leg3":{"px":2.750757593792464e-16,"py":0.12261794783087376,"pz":2.246164033342225,"ry":360,"rx":90}}}