# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-0.2884f,-0.0479f,0.9563f,0f,-0.0803f,0.9964f,0.0257f,1.625f,-0.9541f,-0.0694f,-0.2913f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body1) {transformation: [-0.0698f,0f,0.9976f,0f,0f,1f,0f,1.5625f,-0.9976f,0f,-0.0698f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper_arm) {transformation: [-0.0698f,0.0522f,0.9962f,0.0126f,0f,0.9986f,-0.0523f,1.6708f,-0.9976f,-0.0037f,-0.0697f,-0.0009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm) {transformation: [-0.0698f,0.0522f,0.9962f,-0.4526f,0f,0.9986f,-0.0523f,1.132f,-0.9976f,-0.0037f,-0.0697f,0.0316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper_arm1) {transformation: [0.2087f,-0.6099f,0.7645f,-0.0796f,-0.9461f,-0.3239f,-0.0002f,1.3566f,0.2478f,-0.7233f,-0.6446f,-0.0012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield3) {transformation: [0f,0f,0f,0.5706f,0f,0f,0f,1.72f,0f,0f,0f,0.5761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield2) {transformation: [0f,0f,0f,0.8095f,0f,0f,0f,1.7199f,0f,0f,0f,0.3746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield1) {transformation: [0f,0f,0f,0.8095f,0f,0f,0f,1.7199f,0f,0f,0f,0.3746f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blade) {transformation: [0f,0f,0f,0.7743f,0f,0f,0f,1.6897f,0f,0f,0f,0.3328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_edge) {transformation: [0f,0f,0f,0.7743f,0f,0f,0f,1.6897f,0f,0f,0f,0.3328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm1) {transformation: [0.3114f,-0.5644f,0.7645f,0.5979f,-0.8755f,-0.4833f,-0.0002f,1.5387f,0.3696f,-0.6693f,-0.6446f,0.1236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}