# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:archdemon/animations/idle/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.idle.frame 1