# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_bh1/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.pink_bh1.node.bone2] run data merge entity @s { transformation: [-1f,0f,0f,-0.0245f,0f,1f,0f,0.2125f,0f,0f,-1f,-0.0532f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.pink_bh1.node.bone1] run data merge entity @s { transformation: [-1f,0f,0f,-0.0558f,0f,1f,0f,0.1968f,0f,0f,-1f,-0.0688f,0f,0f,0f,1f], start_interpolation: -1 }