# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_star_skill1/animations/1/zzz/apply_frame {frame: 120}
scoreboard players add @s aj.1.frame 1