# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.0574f,0.4931f,1.375f,0f,0.4931f,-1.0574f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.1354f,0f,1.375f,0f,0f,-1.1354f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.9375f,0f,0f,0f,1.5625f,0f,0f,0f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.2879f,0f,0.3451f,-0.9375f,0f,1.3333f,0f,3f,-0.3451f,0f,-1.2879f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-0.8117f,0f,-1.0578f,1f,0f,1.3333f,0f,2.9375f,1.0578f,0f,-0.8117f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0.0156f,0f,1.136f,0.1496f,3.25f,0f,0.1496f,-1.136f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0464f,0f,-0.2804f,0f,0f,1.1821f,0f,2f,0.2804f,0f,-1.0464f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1.5992f,0f,1.3024f,-0.3681f,0f,2.0625f,0f,3.14f,-1.3024f,0f,-1.5992f,-0.8194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-1.6364f,0f,-1.3327f,0.135f,0f,2.1104f,0f,3.14f,1.3327f,0f,-1.6364f,-0.9062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0.015624999999999915,"py":3.292351737534194,"pz":0.698468812386138,"ry":0,"rx":7.5}}}