# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.interaction1
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.interaction2
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.interaction3
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.hitbox1
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.hitbox2
function animated_java:global/remove/entity_stack_by_uuid with entity @s data.locators.hitbox3