# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.8018f,0f,0f,0f,0.2496f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3131f,-0.2315f,3.2174f,0f,-0.2315f,-1.3131f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3131f,-0.2315f,3.2174f,0f,-0.2315f,-1.3131f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.0176f,-0.5267f,3.2771f,0f,-0.5267f,-1.0176f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1773f,0f,2f,0f,0f,-1.0833f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1.6195f,0f,1.2772f,-0.25f,0f,2.0625f,0f,3.1385f,-1.2772f,0f,-1.6195f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-1.6571f,0f,-1.3069f,0.25f,0f,2.1104f,0f,3.1385f,1.3069f,0f,-1.6571f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-6.09402604261129e-17,"py":3.675382576740028,"pz":0.4976149896324547,"ry":0,"rx":-27.363281250000004}}}