# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.6868f,0f,0f,0f,0.2496f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3131f,-0.2315f,3.1025f,0f,-0.2315f,-1.3131f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3131f,-0.2315f,3.1025f,0f,-0.2315f,-1.3131f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1454f,-0.0324f,3.2571f,0f,-0.0324f,-1.1454f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1079f,0f,2f,0f,0f,-1.0833f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0306f,0f,0.3616f,-0.25f,0f,2.0625f,0f,3.1285f,-0.3616f,0f,-2.0306f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0777f,0f,-0.37f,0.25f,0f,2.1104f,0f,3.1285f,0.37f,0f,-2.0777f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-7.607673065752331e-17,"py":3.3997110795206757,"pz":0.6212136487882947,"ry":0,"rx":-1.6210937500000004}}}