# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.7218f,0f,0f,0f,0.2989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3042f,-0.2772f,3.1279f,0f,-0.2772f,-1.3042f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3042f,-0.2772f,3.1279f,0f,-0.2772f,-1.3042f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1428f,-0.0831f,3.259f,0f,-0.0831f,-1.1428f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1147f,0f,2f,0f,0f,-1.0833f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0102f,0f,0.4616f,-0.25f,0f,2.0625f,0f,3.1295f,-0.4616f,0f,-2.0102f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0569f,0f,-0.4724f,0.25f,0f,2.1104f,0f,3.1295f,0.4724f,0f,-2.0569f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-7.522874508690364e-17,"py":3.429042845390103,"pz":0.6142893211273717,"ry":0,"rx":-4.1587499999999995}}}