# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.7573f,0f,0f,0f,0.3478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.2937f,-0.3226f,3.1521f,0f,-0.3226f,-1.2937f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.2937f,-0.3226f,3.1521f,0f,-0.3226f,-1.2937f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1377f,-0.1362f,3.2611f,0f,-0.1362f,-1.1377f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1219f,0f,2f,0f,0f,-1.0833f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1.9835f,0f,0.5655f,-0.25f,0f,2.0625f,0f,3.1306f,-0.5655f,0f,-1.9835f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0295f,0f,-0.5786f,0.25f,0f,2.1104f,0f,3.1306f,0.5786f,0f,-2.0295f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-7.417800873638705e-17,"py":3.459524189347309,"pz":0.6057094077086771,"ry":0,"rx":-6.82703125}}}