# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:spell_extra/animations/use/zzz/apply_frame {frame: 25}
scoreboard players add @s aj.use.frame 1