# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.piglin_girl_npc_head.root] run return 0
execute if entity @s[tag=aj.piglin_girl_npc_head.animation.nothing.playing] run function animated_java:piglin_girl_npc_head/animations/nothing/zzz/on_tick
execute on passengers run rotate @s ~ ~