# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gray_waterball.root] run return 0
execute if entity @s[tag=aj.gray_waterball.animation.shake.playing] run function animated_java:gray_waterball/animations/shake/zzz/on_tick