# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gray_battle_boss_weapon.root] run return 0
execute if entity @s[tag=aj.gray_battle_boss_weapon.animation.battle_spawn.playing] run function animated_java:gray_battle_boss_weapon/animations/battle_spawn/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_weapon.animation.battle_ranged_greatsword.playing] run function animated_java:gray_battle_boss_weapon/animations/battle_ranged_greatsword/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_weapon.animation.battle_ranged_sword_beam.playing] run function animated_java:gray_battle_boss_weapon/animations/battle_ranged_sword_beam/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_weapon.animation.battle_melee_2.playing] run function animated_java:gray_battle_boss_weapon/animations/battle_melee_2/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_weapon.animation.battle_melee_3.playing] run function animated_java:gray_battle_boss_weapon/animations/battle_melee_3/zzz/on_tick
execute if entity @s[tag=aj.gray_battle_boss_weapon.animation.battle_melee_4.playing] run function animated_java:gray_battle_boss_weapon/animations/battle_melee_4/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:gray_battle_boss_weapon/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~