# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.big_hoglin_head.animation.roar.playing
tag @s remove aj.big_hoglin_head.animation.nothing.playing
tag @s remove aj.big_hoglin_head.animation.attack.playing
tag @s remove aj.big_hoglin_head.animation.die.playing
tag @s remove aj.big_hoglin_head.animation.die_roar.playing