# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.nothing.frame
scoreboard objectives remove aj.angry.frame
scoreboard objectives remove aj.nothing_battle.frame
scoreboard objectives remove aj.dagger_sprint.frame
scoreboard objectives remove aj.dagger_sprint_end.frame
scoreboard objectives remove aj.battle.frame
scoreboard objectives remove aj.axe_jump.frame
scoreboard objectives remove aj.axe_jump_end.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:piglin_girl_head)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'piglin_girl_head'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']