# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_white2/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.pink_white2.node.text_display] run data merge entity @s { transformation: [1f,0f,0f,0f,0f,0f,1f,1.0625f,0f,-1f,0f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pink_white2.node.text_display1] run data merge entity @s { transformation: [0.7071f,0.7071f,0f,0f,0f,0f,1f,0.9375f,0.7071f,-0.7071f,0f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pink_white2.node.bone] run data merge entity @s { transformation: [-1.6667f,0f,0f,0f,0f,1.6667f,0f,0.625f,0f,0f,-1.6667f,0f,0f,0f,0f,1f], start_interpolation: 0 }