# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pink_star_skill1.root] run return 0
execute if entity @s[tag=aj.pink_star_skill1.animation.4.playing] run function animated_java:pink_star_skill1/animations/4/zzz/on_tick
execute if entity @s[tag=aj.pink_star_skill1.animation.4_3.playing] run function animated_java:pink_star_skill1/animations/4_3/zzz/on_tick
execute if entity @s[tag=aj.pink_star_skill1.animation.3.playing] run function animated_java:pink_star_skill1/animations/3/zzz/on_tick
execute if entity @s[tag=aj.pink_star_skill1.animation.3_2.playing] run function animated_java:pink_star_skill1/animations/3_2/zzz/on_tick
execute if entity @s[tag=aj.pink_star_skill1.animation.2.playing] run function animated_java:pink_star_skill1/animations/2/zzz/on_tick
execute if entity @s[tag=aj.pink_star_skill1.animation.2_1.playing] run function animated_java:pink_star_skill1/animations/2_1/zzz/on_tick
execute if entity @s[tag=aj.pink_star_skill1.animation.1.playing] run function animated_java:pink_star_skill1/animations/1/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:pink_star_skill1/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~