# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:knightsword/animations/pause_all
tag @s add aj.knightsword.animation.knight_sword_right_ability.playing
scoreboard players set @s aj.knight_sword_right_ability.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:knightsword/animations/knight_sword_right_ability/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only