# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:knightsword rig_hash set value '95622cf1fad366d6f85f1e38176e4d78ade6499af39eb39a9214ef61e428ae46'
scoreboard objectives add aj.knight_sword_left_click.frame dummy
scoreboard objectives add aj.knight_sword_standby.frame dummy
scoreboard objectives add aj.using_knight_sword.frame dummy
scoreboard objectives add aj.knight_sword_right_ability.frame dummy