# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [0.8881f,-0.325f,0.325f,0f,-0.4596f,-0.628f,0.628f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [0.809f,0f,0.5878f,0f,0f,1f,0f,3.0313f,-0.5878f,0f,0.809f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [0.8881f,0.325f,0.325f,0f,0.4596f,-0.628f,-0.628f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_4) {transformation: [-1f,0f,0f,0f,0f,0.2221f,0.975f,1.3612f,0f,0.975f,-0.2221f,3.0702f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_3) {transformation: [-1f,0f,0f,0f,0f,0.2221f,0.975f,2.5191f,0f,0.975f,-0.2221f,2.8065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_2) {transformation: [-1f,0f,0f,0f,0f,0.9647f,0.2633f,2.8153f,0f,0.2633f,-0.9647f,1.7212f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_1) {transformation: [-1f,0f,0f,0f,0f,0.827f,-0.5623f,2.1125f,0f,-0.5623f,-0.827f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg3":{"px":-3.75995758549858e-16,"py":1.3612477026218024,"pz":3.070238364331993,"ry":0,"rx":77.16750000000005}}}