# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [0.7684f,-0.4525f,0.4525f,0f,-0.6399f,-0.5434f,0.5434f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [0.6691f,0f,0.7431f,0f,0f,1f,0f,3.0313f,-0.7431f,0f,0.6691f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [0.7684f,0.4525f,0.4525f,0f,0.6399f,-0.5434f,-0.5434f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_4) {transformation: [-1f,0f,0f,0f,0f,0.3097f,0.9508f,1.965f,0f,0.9508f,-0.3097f,3.0696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_3) {transformation: [-1f,0f,0f,0f,0f,0.3097f,0.9508f,3.0941f,0f,0.9508f,-0.3097f,2.7019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_2) {transformation: [-1f,0f,0f,0f,0f,0.9953f,-0.0965f,2.9855f,0f,-0.0965f,-0.9953f,1.5821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_1) {transformation: [-1f,0f,0f,0f,0f,0.7157f,-0.6984f,2.1125f,0f,-0.6984f,-0.7157f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg3":{"px":-3.759184555418006e-16,"py":1.965004181271376,"pz":3.0696071373683385,"ry":0,"rx":71.96000000000001}}}