# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [0.1304f,-0.7011f,0.7011f,0f,-0.9915f,-0.0922f,0.0922f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [0.1045f,0f,0.9945f,0f,0f,1f,0f,3.0313f,-0.9945f,0f,0.1045f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [0.1304f,0.7011f,0.7011f,0f,0.9915f,-0.0922f,-0.0922f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_4) {transformation: [-1f,0f,0f,0f,0f,0.3017f,0.9534f,2.5503f,0f,0.9534f,-0.3017f,2.4597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_3) {transformation: [-1f,0f,0f,0f,0f,0.3017f,0.9534f,3.6824f,0f,0.9534f,-0.3017f,2.1014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_2) {transformation: [-1f,0f,0f,0f,0f,0.9442f,-0.3292f,3.312f,0f,-0.3292f,-0.9442f,1.0391f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg3_1) {transformation: [-1f,0f,0f,0f,0f,0.2813f,-0.9596f,2.1125f,0f,-0.9596f,-0.2813f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg3":{"px":-3.0122881367147006e-16,"py":2.5502702172967693,"pz":2.4597199280739335,"ry":0,"rx":72.43749999999999}}}