# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.graud_golem.node.leg3_4] at @s run function animated_java:graud_golem/variants/leg3_damage_hurt/zzz/apply_to_node_leg3_4
execute on passengers if entity @s[tag=aj.graud_golem.node.leg3_3] at @s run function animated_java:graud_golem/variants/leg3_damage_hurt/zzz/apply_to_node_leg3_3
execute on passengers if entity @s[tag=aj.graud_golem.node.leg3_2] at @s run function animated_java:graud_golem/variants/leg3_damage_hurt/zzz/apply_to_node_leg3_2
execute on passengers if entity @s[tag=aj.graud_golem.node.leg3_1] at @s run function animated_java:graud_golem/variants/leg3_damage_hurt/zzz/apply_to_node_leg3_1
return 1