# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.calamity_treant_ability6_catch.frame matches 86.. run scoreboard players set @s aj.calamity_treant_ability6_catch.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.calamity_treant_ability6_catch.frame
execute at @s run function animated_java:calamity_treant/animations/calamity_treant_ability6_catch/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.calamity_treant_ability6_catch.frame 1