# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.use.frame matches 26.. run scoreboard players set @s aj.use.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.use.frame
execute at @s run function animated_java:spell_extra/animations/use/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.use.frame 1