# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.gray_gopr.animation.short_take_1.playing] run function animated_java:gray_gopr/animations/short_take_1/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.short_attack_1.playing] run function animated_java:gray_gopr/animations/short_attack_1/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.short_attack_2.playing] run function animated_java:gray_gopr/animations/short_attack_2/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.short_take_2.playing] run function animated_java:gray_gopr/animations/short_take_2/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.short_attack_3.playing] run function animated_java:gray_gopr/animations/short_attack_3/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.short_attack_4.playing] run function animated_java:gray_gopr/animations/short_attack_4/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.short_attack_5.playing] run function animated_java:gray_gopr/animations/short_attack_5/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.short_switch.playing] run function animated_java:gray_gopr/animations/short_switch/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.great_take.playing] run function animated_java:gray_gopr/animations/great_take/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.great_attack_1.playing] run function animated_java:gray_gopr/animations/great_attack_1/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.great_attack_2.playing] run function animated_java:gray_gopr/animations/great_attack_2/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.great_attack_3.playing] run function animated_java:gray_gopr/animations/great_attack_3/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.great_attack_4.playing] run function animated_java:gray_gopr/animations/great_attack_4/zzz/on_tick
execute if entity @s[tag=aj.gray_gopr.animation.great_throw.playing] run function animated_java:gray_gopr/animations/great_throw/zzz/on_tick