# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:spell rig_hash set value '78bc78e889b064224ffcd5ba9cca659cc882ecef9aa776ae2969d5ce35fa1ebb'
scoreboard objectives add aj.idel.frame dummy