# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pink_boss1.root] run return 0
execute if entity @s[tag=aj.pink_boss1.animation.pose1.playing] run function animated_java:pink_boss1/animations/pose1/zzz/on_tick
execute if entity @s[tag=aj.pink_boss1.animation.size.playing] run function animated_java:pink_boss1/animations/size/zzz/on_tick
execute if entity @s[tag=aj.pink_boss1.animation.moeve1.playing] run function animated_java:pink_boss1/animations/moeve1/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:pink_boss1/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~