# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
execute on passengers run rotate @s ~ ~
execute if data entity @s interaction run function ccmini_gray:map/coffin/open