# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^1 ^0 ^0 ~0 ~0
data modify entity @s data.locators.r_arm merge value { px: 1, py: 0, pz: 0, ry: 0, rx: 0 }