# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^2.059375 ^0.8125 ~0 ~0
data modify entity @s data.locators.head merge value { px: 0, py: 2.059375, pz: 0.8125, ry: 0, rx: 0 }