# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.pink_boss1.animation.pose1.playing
tag @s remove aj.pink_boss1.animation.size.playing
tag @s remove aj.pink_boss1.animation.moeve1.playing