# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '3d1178ff3b84d9cb12c2cfaeae19665198e99987f32372dbe40191b3de0f6343'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack