# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gray_sword_beam.root] run return 0
execute if entity @s[tag=aj.gray_sword_beam.animation.battle_ranged_sword_beam.playing] run function animated_java:gray_sword_beam/animations/battle_ranged_sword_beam/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:gray_sword_beam/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~