# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5723f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3333f,0f,3.0098f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3333f,0f,3.0098f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1454f,0.0312f,3.2549f,0f,0.0312f,-1.1454f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1002f,0.0075f,2f,0f,0.0075f,-1.1002f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0594f,0f,0.1124f,-0.25f,0f,2.0625f,0f,3.125f,-0.1124f,0f,-2.0594f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.1073f,0f,-0.115f,0.25f,0f,2.1104f,0f,3.125f,0.115f,0f,-2.1073f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-7.692937686565572e-17,"py":3.3627942160138327,"pz":0.6281760334425971,"ry":0,"rx":1.5624999999999998}}}