# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5823f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3333f,0f,3.0198f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3333f,0f,3.0198f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1441f,0.0632f,3.2599f,0f,0.0632f,-1.1441f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1175f,0.0154f,2f,0f,0.0154f,-1.1175f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0499f,0f,0.2273f,-0.25f,0f,2.0625f,0f,3.125f,-0.2273f,0f,-2.0499f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0976f,0f,-0.2326f,0.25f,0f,2.1104f,0f,3.125f,0.2326f,0f,-2.0976f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-7.726867872750509e-17,"py":3.3502001151656056,"pz":0.6309466434020206,"ry":0,"rx":3.1640625000000004}}}