# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5868f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3333f,0f,3.0243f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3333f,0f,3.0243f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1432f,0.0776f,3.2621f,0f,0.0776f,-1.1432f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1252f,0.0191f,2f,0f,0.0191f,-1.1252f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0436f,0f,0.2787f,-0.25f,0f,2.0625f,0f,3.125f,-0.2787f,0f,-2.0436f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.0911f,0f,-0.2852f,0.25f,0f,2.1104f,0f,3.125f,0.2852f,0f,-2.0911f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-7.740144929351547e-17,"py":3.3445194250577273,"pz":0.6320307973483079,"ry":0,"rx":3.8834375000000008}}}