# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.6185f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.3333f,0f,3.056f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.3333f,0f,3.056f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1319f,0.1785f,3.278f,0f,0.1785f,-1.1319f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1795f,0.0461f,2f,0f,0.0461f,-1.1795f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1.9624f,0f,0.6346f,-0.25f,0f,2.0625f,0f,3.125f,-0.6346f,0f,-1.9624f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.008f,0f,-0.6494f,0.25f,0f,2.1104f,0f,3.125f,0.6494f,0f,-2.008f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-7.799058202210163e-17,"py":3.3041341074483226,"pz":0.6368414311489788,"ry":0,"rx":8.959999999999996}}}