# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:big_hoglin/animations/pause_all
tag @s add aj.big_hoglin.animation.die_nothing.playing
scoreboard players set @s aj.die_nothing.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:big_hoglin/animations/die_nothing/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only