# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.cafe_make.frame matches 181.. run scoreboard players set @s aj.cafe_make.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.cafe_make.frame
execute at @s run function animated_java:piglin_girl_npc/animations/cafe_make/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.cafe_make.frame 1