# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl_npc/animations/pause_all
scoreboard players set @s aj.cafe_make.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:piglin_girl_npc/animations/cafe_make/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only