# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from entity @s data.locators.head.uuid
function animated_java:big_hoglin/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.r_arm.uuid
function animated_java:big_hoglin/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.l_arm.uuid
function animated_java:big_hoglin/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args