# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.small_jump.frame matches 26.. run scoreboard players set @s aj.small_jump.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.small_jump.frame
execute at @s run function animated_java:big_hoglin/animations/small_jump/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.small_jump.frame 1