# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.short_switch.frame matches 51.. run scoreboard players set @s aj.short_switch.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.short_switch.frame
execute at @s run function animated_java:gray_gopr/animations/short_switch/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.short_switch.frame 1