# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_hair) {transformation: [-0.8f,0f,0f,0.0156f,0f,0.8f,0f,-0.3931f,0f,0f,-0.8f,0.0003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_eyebrow) {transformation: [-0.8f,0f,0f,0.1389f,0f,0.8f,0f,0.1821f,0f,0f,-0.8f,0.2523f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_eye) {transformation: [-0.8f,0f,0f,0.1576f,0f,0.8f,0f,0.1318f,0f,0f,-0.8f,0.2517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_eyebrow) {transformation: [-0.8f,0f,0f,-0.0994f,0f,0.8f,0f,0.1819f,0f,0f,-0.8f,0.2523f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_eye) {transformation: [-0.8f,0f,0f,-0.1064f,0f,0.8f,0f,0.1319f,0f,0f,-0.8f,0.2517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_mouth) {transformation: [-0.8f,0f,0f,0.0156f,0f,0.8f,0f,-0.0381f,0f,0f,-0.8f,0.2508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.8f,0f,0f,0.0155f,0f,0.8f,0f,-0.0906f,0f,0f,-0.8f,0.0014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}