# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp args
$execute store result storage animated_java:temp args.frame int 1 run scoreboard players set @s aj.pose1.frame $(frame)
execute at @s run function animated_java:pink_boss1/animations/pose1/zzz/apply_frame with storage animated_java:temp args