# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_body.node.body1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_body.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_body.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_body.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out