# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '30f1bc2f91977792b3ec624e9679d6f6ce819052de8b3754b838143502c5d7bf'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack