# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_black1__/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.pink_black1__.node.text_display] run data merge entity @s { transformation: [0.7071f,0.7071f,0f,0f,-0.7071f,0.7071f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0 }