# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '9dedd01c7a9b77b2131a12f4c11f3e27a43d66c491e2fb82c8eaff48f5e33679'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack