# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(text_display_text_display) {transformation: [2f,0f,0f,0f,0f,0f,2f,1.0625f,0f,-2f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(text_display_text_display1) {transformation: [0f,0f,0f,0f,0f,0f,0f,0.9375f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone) {transformation: [-1.6667f,0f,0f,0f,0f,1.6667f,0f,0.625f,0f,0f,-1.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}