# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
tag @s add gray.temp
function ccmini_gray:skills/grit_of_pristine_revival/shortsword/rightclick/switch
playsound minecraft:entity.wither.spawn player @a ~ ~ ~ 1 1
tag @s remove gray.temp