# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
playsound minecraft:entity.player.attack.sweep player @a ~ ~ ~ 2 0.8
playsound item.trident.throw player @a ~ ~ ~ 2 0.1
tag @s add gray.temp
function ccmini_gray:skills/grit_of_pristine_revival/greatsword/damage_1
tag @s remove gray.temp