# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
tag @s add gray.temp
function ccmini_gray:skills/grit_of_pristine_revival/greatsword/damage_1
function ccmini_gray:skills/grit_of_pristine_revival/greatsword/break
tag @s remove gray.temp