# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
tag @s add gray.temp
function ccmini_gray:skills/grit_of_pristine_revival/greatsword/damage_1
function ccmini_gray:skills/grit_of_pristine_revival/greatsword/break
tag @s remove gray.temp
execute unless block ~ ~-0.5 ~ #ccmini_gray:transparent run particle block{block_state:{Name:stone}} ~ ~ ~ 0 0 0 0 50