# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ccmini_gray:map/boss/battle/skill/melee/melee_2/sword_damage
playsound item.mace.smash_air hostile @a ~ ~ ~ 0.3 0.7