# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl_npc/root/on_tick/select_locator_head_cheak with entity @s data.locators.head_cheak
function animated_java:piglin_girl_npc/root/on_tick/select_locator_locator with entity @s data.locators.locator