# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:calamity_treant/animations/pause_all
tag @s add aj.calamity_treant.animation.calamity_treant_dead.playing
scoreboard players set @s aj.calamity_treant_dead.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:calamity_treant/animations/calamity_treant_dead/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only