# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'a39ce31a5440f374f3e0a32734d74f5544bd7d986768bca26247fb5efbb1f377'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack