# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gray_guide rig_hash set value '81f42c647a27ba30b79622d063ee86acc58e75860630bd07275b8384c5e79291'
scoreboard objectives add aj.shake.frame dummy