# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:big_hoglin_head rig_hash set value '37663210d9fabb109660be7941214fd2afd7a18541b1835f4bc275c43fdf0c78'
scoreboard objectives add aj.roar.frame dummy
scoreboard objectives add aj.nothing.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.die.frame dummy
scoreboard objectives add aj.die_roar.frame dummy