# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [0.9922f,-0.088f,0.088f,0f,-0.1244f,-0.7016f,0.7016f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [0.9781f,0f,0.2079f,0f,0f,1f,0f,3.0313f,-0.2079f,0f,0.9781f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [0.9922f,0.088f,0.088f,0f,0.1244f,-0.7016f,-0.7016f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_4) {transformation: [-1f,0f,0f,0f,0f,0.0652f,-0.9979f,0.344f,0f,-0.9979f,-0.0652f,-2.5389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_3) {transformation: [-1f,0f,0f,0f,0f,0.0652f,-0.9979f,1.5289f,0f,-0.9979f,-0.0652f,-2.4615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_2) {transformation: [-1f,0f,0f,0f,0f,0.518f,-0.8554f,2.4912f,0f,-0.8554f,-0.518f,-1.8787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_1) {transformation: [-1f,0f,0f,0f,0f,0.953f,0.303f,2.1125f,0f,0.303f,-0.953f,-0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg4":{"px":3.1092395901579703e-16,"py":0.34395750207882814,"pz":-2.5388867976650435,"ry":0,"rx":-86.2625000000001}}}