# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [-0.8881f,-0.325f,0.325f,0f,-0.4596f,0.628f,-0.628f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [-0.809f,0f,0.5878f,0f,0f,1f,0f,3.0313f,-0.5878f,0f,-0.809f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [-0.8881f,0.325f,0.325f,0f,0.4596f,0.628f,0.628f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_4) {transformation: [-1f,0f,0f,0f,0f,0.0388f,-0.9992f,0.7921f,0f,-0.9992f,-0.0388f,-2.4072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_3) {transformation: [-1f,0f,0f,0f,0f,0.0388f,-0.9992f,1.9787f,0f,-0.9992f,-0.0388f,-2.3612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_2) {transformation: [-1f,0f,0f,0f,0f,0.6062f,-0.7953f,2.8735f,0f,-0.7953f,-0.6062f,-1.6792f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_1) {transformation: [-1f,0f,0f,0f,0f,0.7934f,0.6088f,2.1125f,0f,0.6088f,-0.7934f,-0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg4":{"px":2.947976816742073e-16,"py":0.7921134814940733,"pz":-2.4072057500942874,"ry":0,"rx":-87.77777777777791}}}