# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [0.9594f,-0.1993f,0.1993f,0f,-0.2819f,-0.6784f,0.6784f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [0.9135f,0f,0.4067f,0f,0f,1f,0f,3.0313f,-0.4067f,0f,0.9135f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [0.9594f,0.1993f,0.1993f,0f,0.2819f,-0.6784f,-0.6784f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_4) {transformation: [-1f,0f,0f,0f,0f,0.1668f,-0.986f,0.7759f,0f,-0.986f,-0.1668f,-2.9013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_3) {transformation: [-1f,0f,0f,0f,0f,0.1668f,-0.986f,1.9467f,0f,-0.986f,-0.1668f,-2.7033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_2) {transformation: [-1f,0f,0f,0f,0f,0.7856f,-0.6187f,2.6427f,0f,-0.6187f,-0.7856f,-1.8195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_1) {transformation: [-1f,0f,0f,0f,0f,0.9056f,0.4242f,2.1125f,0f,0.4242f,-0.9056f,-0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg4":{"px":3.553122852832507e-16,"py":0.7758609767442779,"pz":-2.9013449880458015,"ry":0,"rx":-80.40000000000006}}}