# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [0.7684f,-0.4525f,0.4525f,0f,-0.6399f,-0.5434f,0.5434f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [0.6691f,0f,0.7431f,0f,0f,1f,0f,3.0313f,-0.7431f,0f,0.6691f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [0.7684f,0.4525f,0.4525f,0f,0.6399f,-0.5434f,-0.5434f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_4) {transformation: [-1f,0f,0f,0f,0f,0.3843f,-0.9232f,1.9978f,0f,-0.9232f,-0.3843f,-3.1582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_3) {transformation: [-1f,0f,0f,0f,0f,0.3843f,-0.9232f,3.0941f,0f,-0.9232f,-0.3843f,-2.7019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_2) {transformation: [-1f,0f,0f,0f,0f,0.9953f,0.0965f,2.9855f,0f,0.0965f,-0.9953f,-1.5821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_1) {transformation: [-1f,0f,0f,0f,0f,0.7157f,0.6984f,2.1125f,0f,0.6984f,-0.7157f,-0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg4":{"px":3.8676939547370425e-16,"py":1.997815201558233,"pz":-3.1582117859858707,"ry":0,"rx":-67.4}}}