# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_core) {transformation: [-0.3798f,-0.6541f,0.6541f,0f,-0.9251f,0.2685f,-0.2685f,3.0313f,0f,-0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_case) {transformation: [-0.309f,0f,0.9511f,0f,0f,1f,0f,3.0313f,-0.9511f,0f,-0.309f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_ball) {transformation: [-0.3798f,0.6541f,0.6541f,0f,0.9251f,0.2685f,0.2685f,2.0938f,0f,0.7071f,-0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_4) {transformation: [-1f,0f,0f,0f,0f,0.1197f,-0.9928f,2.1804f,0f,-0.9928f,-0.1197f,-2.0476f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_3) {transformation: [-1f,0f,0f,0f,0f,0.1197f,-0.9928f,3.3594f,0f,-0.9928f,-0.1197f,-1.9054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_2) {transformation: [-1f,0f,0f,0f,0f,1f,0.0003f,3.359f,0f,0.0003f,-1f,-0.7804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg4_1) {transformation: [-1f,0f,0f,0f,0f,0.0743f,0.9972f,2.1125f,0f,0.9972f,-0.0743f,-0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"leg4":{"px":2.5075954176128904e-16,"py":2.180430827373632,"pz":-2.047607048300601,"ry":0,"rx":-83.12250000000006}}}