# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl_npc/animations/pause_all
tag @s add aj.piglin_girl_npc.animation.rotate.playing
scoreboard players set @s aj.rotate.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:piglin_girl_npc/animations/rotate/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only