# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:piglin_girl_npc rig_hash set value '215519705ddd82b21c4aec2d3a758bb847707aa60cdf66c62d33545154b17d46'
scoreboard objectives add aj.cafe_make.frame dummy
scoreboard objectives add aj.sit.frame dummy
scoreboard objectives add aj.rotate.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.to_sit.frame dummy