# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_sword_beam/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.gray_sword_beam.node.gray_sword_beam] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }