# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0.06313625 ^1.2572075 ^-0.20055875 ~0 ~0
data modify entity @s data.locators.locator merge value { px: 0.06313625, py: 1.2572075, pz: -0.20055875, ry: 0, rx: 0 }