# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0.44569625 ^3.152165625 ^0.086545625 ~0 ~0
data modify entity @s data.locators.locator2 merge value { px: 0.44569625, py: 3.152165625, pz: 0.086545625, ry: 0, rx: 0 }