# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper_arm1) {transformation: [0.2336f,-0.6873f,0.6878f,-0.0746f,-0.487f,0.5295f,0.6946f,1.3528f,-0.8415f,-0.4972f,-0.2111f,-0.0447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield3) {transformation: [0f,0f,0f,0.85f,0f,0f,0f,1.1771f,0f,0f,0f,0.3694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield2) {transformation: [0f,0f,0f,0.85f,0f,0f,0f,1.1771f,0f,0f,0f,0.3694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield1) {transformation: [0f,0f,0f,0.85f,0f,0f,0f,1.1771f,0f,0f,0f,0.3694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blade) {transformation: [0f,0f,0f,0.8105f,0f,0f,0f,1.2074f,0f,0f,0f,0.3316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_edge) {transformation: [0f,0f,0f,0.8105f,0f,0f,0f,1.2074f,0f,0f,0f,0.3316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm1) {transformation: [0.3102f,-0.6321f,0.7101f,0.613f,-0.5568f,0.4846f,0.6746f,1.3589f,-0.7705f,-0.6047f,-0.2016f,0.1426f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}