# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper_arm1) {transformation: [0.3402f,-0.8961f,0.2852f,-0.0009f,-0.7042f,-0.0418f,0.7087f,1.2056f,-0.6231f,-0.442f,-0.6453f,0.1048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield3) {transformation: [0f,0f,0f,0.9212f,0f,0f,0f,1.599f,0f,0f,0f,0.2969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield2) {transformation: [0f,0f,0f,0.9212f,0f,0f,0f,1.599f,0f,0f,0f,0.2969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield1) {transformation: [0f,0f,0f,0.9212f,0f,0f,0f,1.599f,0f,0f,0f,0.2969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blade) {transformation: [0f,0f,0f,0.8723f,0f,0f,0f,1.589f,0f,0f,0f,0.2593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_edge) {transformation: [0f,0f,0f,0.8723f,0f,0f,0f,1.589f,0f,0f,0f,0.2593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm1) {transformation: [0.5241f,-0.7822f,0.3367f,0.6279f,-0.691f,-0.1595f,0.705f,1.5392f,-0.4978f,-0.6022f,-0.6241f,0.0711f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}