# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper_arm1) {transformation: [0.3716f,-0.9164f,0.1487f,0.0366f,-0.7528f,-0.2037f,0.6259f,1.191f,-0.5433f,-0.3446f,-0.7656f,0.1667f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield3) {transformation: [0f,0f,0f,0.9089f,0f,0f,0f,1.7117f,0f,0f,0f,0.2205f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield2) {transformation: [0f,0f,0f,0.9089f,0f,0f,0f,1.7117f,0f,0f,0f,0.2205f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield1) {transformation: [0f,0f,0f,0.9089f,0f,0f,0f,1.7117f,0f,0f,0f,0.2205f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blade) {transformation: [0f,0f,0f,0.8603f,0f,0f,0f,1.6896f,0f,0f,0f,0.188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_edge) {transformation: [0f,0f,0f,0.8603f,0f,0f,0f,1.6896f,0f,0f,0f,0.188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm1) {transformation: [0.5919f,-0.7781f,0.2102f,0.6172f,-0.6886f,-0.3527f,0.6335f,1.5794f,-0.4188f,-0.5198f,-0.7446f,0.0256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}