# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper_arm1) {transformation: [0.3923f,-0.9181f,0.0571f,0.0649f,-0.7801f,-0.2992f,0.5495f,1.191f,-0.4874f,-0.2601f,-0.8335f,0.2091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield3) {transformation: [0f,0f,0f,0.891f,0f,0f,0f,1.7772f,0f,0f,0f,0.1582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield2) {transformation: [0f,0f,0f,0.891f,0f,0f,0f,1.7772f,0f,0f,0f,0.1582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield1) {transformation: [0f,0f,0f,0.891f,0f,0f,0f,1.7772f,0f,0f,0f,0.1582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blade) {transformation: [0f,0f,0f,0.8435f,0f,0f,0f,1.7476f,0f,0f,0f,0.1303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_edge) {transformation: [0f,0f,0f,0.8435f,0f,0f,0f,1.7476f,0f,0f,0f,0.1303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm1) {transformation: [0.6385f,-0.7593f,0.1257f,0.6062f,-0.6744f,-0.4733f,0.5667f,1.5997f,-0.3709f,-0.4466f,-0.8143f,-0.0093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}