# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper_arm1) {transformation: [0.4047f,-0.9144f,0.0019f,0.083f,-0.7944f,-0.3506f,0.4959f,1.1949f,-0.4528f,-0.2022f,-0.8684f,0.2344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield3) {transformation: [0f,0f,0f,0.8755f,0f,0f,0f,1.8127f,0f,0f,0f,0.1174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield2) {transformation: [0f,0f,0f,0.8755f,0f,0f,0f,1.8127f,0f,0f,0f,0.1174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield1) {transformation: [0f,0f,0f,0.8755f,0f,0f,0f,1.8127f,0f,0f,0f,0.1174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blade) {transformation: [0f,0f,0f,0.8293f,0f,0f,0f,1.7788f,0f,0f,0f,0.0926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_edge) {transformation: [0f,0f,0f,0.8293f,0f,0f,0f,1.7788f,0f,0f,0f,0.0926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm1) {transformation: [0.6689f,-0.7395f,0.0754f,0.5982f,-0.6591f,-0.5432f,0.5202f,1.609f,-0.3437f,-0.3977f,-0.8507f,-0.0317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}