# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper_arm1) {transformation: [0.411f,-0.9112f,-0.0262f,0.0926f,-0.8012f,-0.3748f,0.4665f,1.198f,-0.4349f,-0.1708f,-0.8841f,0.2472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield3) {transformation: [0f,0f,0f,0.8654f,0f,0f,0f,1.8303f,0f,0f,0f,0.0965f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield2) {transformation: [0f,0f,0f,0.8654f,0f,0f,0f,1.8303f,0f,0f,0f,0.0964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield1) {transformation: [0f,0f,0f,0.8654f,0f,0f,0f,1.8303f,0f,0f,0f,0.0964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blade) {transformation: [0f,0f,0f,0.8201f,0f,0f,0f,1.794f,0f,0f,0f,0.0731f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_edge) {transformation: [0f,0f,0f,0.8201f,0f,0f,0f,1.794f,0f,0f,0f,0.0731f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm1) {transformation: [0.6875f,-0.7245f,0.0506f,0.5937f,-0.6472f,-0.5795f,0.4953f,1.6129f,-0.3295f,-0.3733f,-0.8673f,-0.0435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}