# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper_arm1) {transformation: [0.4134f,-0.9098f,-0.0365f,0.0961f,-0.8036f,-0.3833f,0.4553f,1.1994f,-0.4283f,-0.1589f,-0.8896f,0.2519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield3) {transformation: [0f,0f,0f,0.8604f,0f,0f,0f,1.8372f,0f,0f,0f,0.0894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield2) {transformation: [0f,0f,0f,0.8604f,0f,0f,0f,1.8372f,0f,0f,0f,0.0894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_shield1) {transformation: [0f,0f,0f,0.8604f,0f,0f,0f,1.8372f,0f,0f,0f,0.0894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blade) {transformation: [0f,0f,0f,0.8157f,0f,0f,0f,1.8f,0f,0f,0f,0.0665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_edge) {transformation: [0f,0f,0f,0.8157f,0f,0f,0f,1.8f,0f,0f,0f,0.0665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_forearm1) {transformation: [0.697f,-0.7158f,0.0423f,0.592f,-0.6401f,-0.5946f,0.4865f,1.6142f,-0.3231f,-0.3661f,-0.8727f,-0.0479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}