# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl/animations/pause_all
scoreboard players set @s aj.spear_attack2_deal.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:piglin_girl/animations/spear_attack2_deal/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only