# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:graud_golem/animations/pause_all
scoreboard players set @s aj.not_summon.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:graud_golem/animations/not_summon/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only