# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:pink_star_skill1_2 rig_hash set value 'c3d675f8c1068b482d2e426ca01c918cccdd809e06f95a36bb8b620971334ebd'
scoreboard objectives add aj.shoot_r.frame dummy
scoreboard objectives add aj.shoot_l.frame dummy