# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add icer.scourge_staff_gemstone
scoreboard players operation @s icer.scourge_staff_gemstone.number = aj.last_id aj.id
function animated_java:global/util/get_entity_stack_uuids