# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gray_sandstorm rig_hash set value 'b3c17b029516e84b8e22f8265f4c7b430941a2f9c8e2825efb2b13c3bd5f2636'
scoreboard objectives add aj.sandstorm.frame dummy