# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_sandstorm/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone2] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5313f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone1] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.0938f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone3] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.9063f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone4] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.3121f,0f,0f,-1f,0.0068f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone5] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone6] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1563f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone7] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.7344f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone8] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.2188f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone9] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.4844f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone10] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.9375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone11] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
execute on passengers if entity @s[tag=aj.gray_sandstorm.node.bone12] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5313f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }