# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.pink_star_skill1_2.animation.shoot_r.playing
tag @s remove aj.pink_star_skill1_2.animation.shoot_l.playing