# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.piglin_girl_head.root] run return 0
execute if entity @s[tag=aj.piglin_girl_head.animation.nothing.playing] run function animated_java:piglin_girl_head/animations/nothing/zzz/on_tick
execute if entity @s[tag=aj.piglin_girl_head.animation.angry.playing] run function animated_java:piglin_girl_head/animations/angry/zzz/on_tick
execute if entity @s[tag=aj.piglin_girl_head.animation.nothing_battle.playing] run function animated_java:piglin_girl_head/animations/nothing_battle/zzz/on_tick
execute if entity @s[tag=aj.piglin_girl_head.animation.dagger_sprint.playing] run function animated_java:piglin_girl_head/animations/dagger_sprint/zzz/on_tick
execute if entity @s[tag=aj.piglin_girl_head.animation.dagger_sprint_end.playing] run function animated_java:piglin_girl_head/animations/dagger_sprint_end/zzz/on_tick
execute if entity @s[tag=aj.piglin_girl_head.animation.battle.playing] run function animated_java:piglin_girl_head/animations/battle/zzz/on_tick
execute if entity @s[tag=aj.piglin_girl_head.animation.axe_jump.playing] run function animated_java:piglin_girl_head/animations/axe_jump/zzz/on_tick
execute if entity @s[tag=aj.piglin_girl_head.animation.axe_jump_end.playing] run function animated_java:piglin_girl_head/animations/axe_jump_end/zzz/on_tick
execute on passengers run rotate @s ~ ~