# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
playsound minecraft:item.spear_wood.hit player @a ~ ~ ~ 1 1
playsound minecraft:entity.player.attack.sweep player @a ~ ~ ~ 0.8 1.5
tag @s add gray.temp
tag @s add gray.temp
function ccmini_gray:skills/grit_of_pristine_revival/shortsword/mode_1/damage_3
function ccmini_gray:skills/grit_of_pristine_revival/shortsword/attack_end
tag @s remove gray.temp