# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '6f622937776bda04c6d898ec4b2c31f8097a749242bd34924e79cb43b8e38b2a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack