# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.great_throw.frame matches 41.. run scoreboard players set @s aj.great_throw.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.great_throw.frame
execute at @s run function animated_java:gray_gopr/animations/great_throw/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.great_throw.frame 1