# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_feet.node.left_leg_up] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_leg_up set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_feet.node.left_leg_down] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_leg_down set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_feet.node.right_leg_up] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_leg_up set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_feet.node.right_leg_down] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_leg_down set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_feet.node.group2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_group2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.gray_battle_boss_feet.node.group] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_group set from storage animated_java:gu out