# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.attack_run.frame matches 31.. run scoreboard players set @s aj.attack_run.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.attack_run.frame
execute at @s run function animated_java:archdemon/animations/attack_run/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.attack_run.frame 1