# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:gray_battle_boss_feet rig_hash set value '09e8551158208e7f33a81d7a5f675d41192388088c8b61cce84a2edc06f68447'
scoreboard objectives add aj.battle_.frame dummy
scoreboard objectives add aj.battle_spawn.frame dummy
scoreboard objectives add aj.battle_ranged_walk.frame dummy
scoreboard objectives add aj.battle_ranged_sword_beam.frame dummy
scoreboard objectives add aj.battle_melee_walk.frame dummy
scoreboard objectives add aj.battle_melee_2.frame dummy
scoreboard objectives add aj.battle_melee_4.frame dummy