# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tp @s ~ ~ ~ ~ ~
playsound minecraft:entity.player.attack.sweep player @a ~ ~ ~ 0.8 1.5
playsound minecraft:item.trident.throw player @a ~ ~ ~ 1 1.2
tag @s add gray.temp
function ccmini_gray:skills/grit_of_pristine_revival/shortsword/mode_0/damage_1
tag @s remove gray.temp