# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.global.data] run function animated_java:gray_battle_boss_weapon/animations/battle_ranged_sword_beam/zzz/frames/$(frame) with entity @s data.uuids_by_name
return 1