# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon minecraft:marker ^0 ^3.375 ^0.625 {Tags:["aj.archdemon.bone.head.child","aj.archdemon.bone.head.child.locator","aj.archdemon.bone.head.decendant","aj.archdemon.bone.head.decendant.locator","aj.archdemon.bone.head.tree","aj.archdemon.entity","aj.archdemon.locator","aj.archdemon.locator.locator","aj.archdemon.node","aj.archdemon.node.locator","aj.global.bone.head.child","aj.global.bone.head.child.locator","aj.global.bone.head.decendant","aj.global.bone.head.decendant.locator","aj.global.bone.head.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.locator","aj.new"]}
execute as @n[ type=minecraft:marker, tag=aj.archdemon.locator.locator, tag=aj.new, distance=..4 ] run function animated_java:archdemon/zzz/summon/as_data_entity/as_locator/locator
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_locator set from storage animated_java:gu out
data modify entity @s data.locators.locator.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.archdemon.node.left_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.archdemon.node.right_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.archdemon.node.item_display] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.archdemon.node.right_hand] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_hand set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.archdemon.node.left_hand] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_hand set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.archdemon.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.archdemon.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.archdemon.node.right_wing] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_wing set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.archdemon.node.left_wing] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_wing set from storage animated_java:gu out