# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.spear_attack2.frame matches 13.. run scoreboard players set @s aj.spear_attack2.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.spear_attack2.frame
execute at @s run function animated_java:piglin_girl/animations/spear_attack2/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.spear_attack2.frame 1