# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl/animations/pause_all
tag @s add aj.piglin_girl.animation.spear_attack2.playing
scoreboard players set @s aj.spear_attack2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:piglin_girl/animations/spear_attack2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only