# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.pink_star_skill1_2.root] run return 0
execute if entity @s[tag=aj.pink_star_skill1_2.animation.shoot_r.playing] run function animated_java:pink_star_skill1_2/animations/shoot_r/zzz/on_tick
execute if entity @s[tag=aj.pink_star_skill1_2.animation.shoot_l.playing] run function animated_java:pink_star_skill1_2/animations/shoot_l/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:pink_star_skill1_2/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~