# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:big_hoglin/animations/run2/zzz/apply_frame {frame: 15}
scoreboard players add @s aj.run2.frame 1