# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:archdemon rig_hash set value 'bbccc3ff37231dd314ba9fb4b83146e201e0ee6187d55c2301e36b9a44b49305'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.idle_run.frame dummy
scoreboard objectives add aj.hellfire.frame dummy
scoreboard objectives add aj.hellfire_run.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.attack_run.frame dummy
scoreboard objectives add aj.run.frame dummy
scoreboard objectives add aj.fly.frame dummy
scoreboard objectives add aj.jump_ready.frame dummy
scoreboard objectives add aj.jump_end.frame dummy
scoreboard objectives add aj.jump_ready_run.frame dummy
scoreboard objectives add aj.sprint_start.frame dummy
scoreboard objectives add aj.sprint_start_run.frame dummy
scoreboard objectives add aj.sprint_end.frame dummy
scoreboard objectives add aj.throw_ice.frame dummy
scoreboard objectives add aj.throw_ice_run.frame dummy
scoreboard objectives add aj.die.frame dummy