# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idle.frame
scoreboard objectives remove aj.idle_run.frame
scoreboard objectives remove aj.hellfire.frame
scoreboard objectives remove aj.hellfire_run.frame
scoreboard objectives remove aj.attack.frame
scoreboard objectives remove aj.attack_run.frame
scoreboard objectives remove aj.run.frame
scoreboard objectives remove aj.fly.frame
scoreboard objectives remove aj.jump_ready.frame
scoreboard objectives remove aj.jump_end.frame
scoreboard objectives remove aj.jump_ready_run.frame
scoreboard objectives remove aj.sprint_start.frame
scoreboard objectives remove aj.sprint_start_run.frame
scoreboard objectives remove aj.sprint_end.frame
scoreboard objectives remove aj.throw_ice.frame
scoreboard objectives remove aj.throw_ice_run.frame
scoreboard objectives remove aj.die.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:archdemon)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'archdemon'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']