# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.big_hoglin_head.node.jaw_dirt] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_jaw_dirt set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.big_hoglin_head.node.jaw] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_jaw set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.big_hoglin_head.node.dirt] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_dirt set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.big_hoglin_head.node.r_ear] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_ear set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.big_hoglin_head.node.l_ear] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_ear set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.big_hoglin_head.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out