# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:boss_box/animations/pause_all
tag @s add aj.boss_box.animation.open_box.playing
scoreboard players set @s aj.open_box.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:boss_box/animations/open_box/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only