# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '0baf7622c3859fbb5a194c3ab88437f75e8c2140ddc0305915bffd11f0a84793'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack