# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail2) {transformation: [-1.4166f,-0.0024f,-0.0073f,-0.04f,0.003f,1.0669f,-0.9321f,2.1656f,0.0071f,-0.9321f,-1.0668f,-2.7685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-1f,-0.0009f,-0.0053f,-0.0348f,0.0021f,0.843f,-0.5379f,2.6867f,0.005f,-0.5379f,-0.843f,-1.9519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2_dirt) {transformation: [-1.5041f,0.0073f,-0.0037f,0f,0.0032f,1.1463f,0.9739f,0.8559f,0.0075f,0.9739f,-1.1463f,-0.473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2) {transformation: [-1.6875f,0.0082f,-0.0041f,0f,0.0035f,1.286f,1.0926f,0.8559f,0.0084f,1.0926f,-1.286f,-0.473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_dirt) {transformation: [-1.1333f,0f,0f,0f,0f,1.0469f,0.4341f,0.7996f,0f,0.4341f,-1.0469f,-0.3779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.8125f,0f,0f,0f,0f,1.6743f,0.6943f,0.7996f,0f,0.6943f,-1.6743f,-0.3779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg2_dirt) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0558f,0f,0f,-1f,-1.0595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg2) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0558f,0f,0f,-1f,-1.0595f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg_dirt) {transformation: [-1.3208f,0f,0f,1f,0f,1.3203f,-0.0384f,2.065f,0f,-0.0384f,-1.3203f,-1.7263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1.3125f,0f,0f,1f,0f,1.3119f,-0.0382f,2.065f,0f,-0.0382f,-1.3119f,-1.7263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg_dirt) {transformation: [-1.3208f,0f,0f,-1f,0f,1.3208f,0.0081f,2.1286f,0f,0.0081f,-1.3208f,-1.8559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg2_dirt) {transformation: [-1f,0f,0f,-1.3125f,0f,0.9996f,0.03f,1.0965f,0f,0.03f,-0.9996f,-1.2251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg2) {transformation: [-1f,0f,0f,-1.3125f,0f,0.9996f,0.03f,1.0965f,0f,0.03f,-0.9996f,-1.2251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1.3125f,0f,0f,-1f,0f,1.3125f,0.0081f,2.1286f,0f,0.0081f,-1.3125f,-1.8559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"head":{"px":-7.192973610650429e-17,"py":0.7207314345495696,"pz":0.5873508684837505,"ry":0,"rx":22.52186588921283}}}