# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail2) {transformation: [-1.4151f,0.0639f,-0.0159f,-0.0461f,0.0477f,1.2305f,0.7004f,2.6518f,0.0454f,0.6991f,-1.2313f,-2.6558f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-0.9989f,0.0386f,-0.026f,-0.0209f,0.0337f,0.9853f,0.1675f,2.4895f,0.0321f,0.1664f,-0.9855f,-1.701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2_dirt) {transformation: [-1.5025f,0.0696f,-0.0065f,0f,0.0507f,1.1802f,0.9312f,0.7135f,0.0482f,0.93f,-1.1812f,-0.1565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2) {transformation: [-1.6857f,0.0781f,-0.0073f,0f,0.0569f,1.324f,1.0447f,0.7135f,0.0541f,1.0434f,-1.3252f,-0.1565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_dirt) {transformation: [-1.1333f,0f,0f,0f,0f,1.1331f,-0.0217f,0.7f,0f,-0.0217f,-1.1331f,-0.0469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.8125f,0f,0f,0f,0f,1.8122f,-0.0348f,0.7f,0f,-0.0348f,-1.8122f,-0.0469f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg2_dirt) {transformation: [-1f,0f,0f,1.3125f,0f,0.9962f,0.0872f,1.2938f,0f,0.0872f,-0.9962f,-1.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg2) {transformation: [-1f,0f,0f,1.3125f,0f,0.9962f,0.0872f,1.2938f,0f,0.0872f,-0.9962f,-1.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg_dirt) {transformation: [-1.3208f,0f,0f,1f,0f,1.3208f,0f,2.3219f,0f,0f,-1.3208f,-1.8559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1.3125f,0f,0f,1f,0f,1.3125f,0f,2.3219f,0f,0f,-1.3125f,-1.8559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg_dirt) {transformation: [-1.3208f,0f,0f,-1f,0f,1.2203f,0.5055f,2.2594f,0f,0.5055f,-1.2203f,-1.4184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg2_dirt) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0657f,0f,0f,-1f,-1.2232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg2) {transformation: [-1f,0f,0f,-1.3125f,0f,1f,0f,1.0657f,0f,0f,-1f,-1.2232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1.3125f,0f,0f,-1f,0f,1.2126f,0.5023f,2.2594f,0f,0.5023f,-1.2126f,-1.4184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"head":{"px":-1.064387527296486e-16,"py":1.01449607399694,"pz":0.8691383736417342,"ry":0,"rx":-1.0986328125}}}