# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail2) {transformation: [-1.4162f,0.0001f,-0.0354f,-0.0544f,0.018f,1.221f,-0.7183f,2.6067f,0.0304f,-0.7185f,-1.2206f,-2.6933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-0.9997f,0.0085f,-0.0235f,-0.0317f,0.0127f,0.9828f,-0.1843f,2.7852f,0.0215f,-0.1845f,-0.9826f,-1.7415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2_dirt) {transformation: [-1.5037f,0.0369f,-0.0073f,0f,0.0191f,1.0014f,1.1222f,0.7683f,0.0323f,1.1217f,-1.0016f,-0.5286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2) {transformation: [-1.687f,0.0413f,-0.0081f,0f,0.0215f,1.1235f,1.259f,0.7683f,0.0363f,1.2585f,-1.1237f,-0.5286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_dirt) {transformation: [-1.1333f,0f,0f,0f,0f,1.0961f,0.288f,0.7254f,0f,0.288f,-1.0961f,-0.4268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.8125f,0f,0f,0f,0f,1.753f,0.4606f,0.7254f,0f,0.4606f,-1.753f,-0.4268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg2_dirt) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0725f,0f,0f,-1f,-0.737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg2) {transformation: [-1f,0f,0f,1.3125f,0f,1f,0f,1.0725f,0f,0f,-1f,-0.737f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg_dirt) {transformation: [-1.3208f,0f,0f,1f,0f,1.3196f,-0.0576f,2.0719f,0f,-0.0576f,-1.3196f,-1.4184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1.3125f,0f,0f,1f,0f,1.3113f,-0.0573f,2.0719f,0f,-0.0573f,-1.3113f,-1.4184f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg_dirt) {transformation: [-1.3208f,0f,0f,-1f,0f,1.3206f,0.0243f,2.2887f,0f,0.0243f,-1.3206f,-1.8559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg2_dirt) {transformation: [-1f,0f,0f,-1.3125f,0f,0.9943f,0.1062f,1.249f,0f,0.1062f,-0.9943f,-1.2378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg2) {transformation: [-1f,0f,0f,-1.3125f,0f,0.9943f,0.1062f,1.249f,0f,0.1062f,-0.9943f,-1.2378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1.3125f,0f,0f,-1f,0f,1.3123f,0.0242f,2.2887f,0f,0.0242f,-1.3123f,-1.8559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"head":{"px":-6.616740377739307e-17,"py":0.778226395908859,"pz":0.5402978542340648,"ry":0,"rx":14.723032069970849}}}