# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl/animations/spear_idle/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.spear_idle.frame 1