# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail2) {transformation: [-1.3831f,0.2289f,-0.204f,0.0114f,0.2168f,1.3966f,0.0973f,3.1524f,0.2168f,0.0637f,-1.3985f,-2.4408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_tail) {transformation: [-0.9763f,0.2095f,-0.0544f,0.0642f,0.153f,0.846f,0.5108f,2.6576f,0.153f,0.4903f,-0.858f,-1.6096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2_dirt) {transformation: [-1.4685f,0.3256f,0f,0f,0.2302f,1.0384f,1.0636f,0.7156f,0.2302f,1.0384f,-1.0636f,-0.2812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body2) {transformation: [-1.6475f,0.3652f,0f,0f,0.2583f,1.165f,1.1932f,0.7156f,0.2583f,1.165f,-1.1932f,-0.2812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body_dirt) {transformation: [-1.1333f,0f,0f,0f,0f,1.1333f,0f,0.7f,0f,0f,-1.1333f,-0.1719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.8125f,0f,0f,0f,0f,1.8125f,0f,0.7f,0f,0f,-1.8125f,-0.1719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg2_dirt) {transformation: [-1f,0f,0f,1.3125f,0f,0.9806f,0.1959f,0.957f,0f,0.1959f,-0.9806f,-1.9268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg2) {transformation: [-1f,0f,0f,1.3125f,0f,0.9806f,0.1959f,0.957f,0f,0.1959f,-0.9806f,-1.9268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlg_dirt) {transformation: [-1.3208f,0f,0f,1f,0f,0.8765f,0.9881f,2.1159f,0f,0.9881f,-0.8765f,-1.5804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1.3125f,0f,0f,1f,0f,0.871f,0.9819f,2.1159f,0f,0.9819f,-0.871f,-1.5804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg_dirt) {transformation: [-1.3208f,0f,0f,-1f,0f,1.2758f,-0.3419f,2.0719f,0f,-0.3419f,-1.2758f,-1.8559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llg2_dirt) {transformation: [-1f,0f,0f,-1.3125f,0f,0.9063f,-0.4226f,1.2437f,0f,-0.4226f,-0.9063f,-0.9743f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg2) {transformation: [-1f,0f,0f,-1.3125f,0f,0.9063f,-0.4226f,1.2437f,0f,-0.4226f,-0.9063f,-0.9743f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1.3125f,0f,0f,-1f,0f,1.2678f,-0.3397f,2.0719f,0f,-0.3397f,-1.2678f,-1.8559f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"head":{"px":-9.184850993605148e-17,"py":0.9968750000000002,"pz":0.75,"ry":0,"rx":0}}}