# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
summon item_display ^0 ^2.0625 ^0.03125 {Tags:["aj.global.bone.all.decendant","aj.global.bone.all.decendant.locator","aj.global.bone.all.tree","aj.global.bone.body1.child","aj.global.bone.body1.child.locator","aj.global.bone.body1.decendant","aj.global.bone.body1.decendant.locator","aj.global.bone.body1.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.head_cheak","aj.new","aj.piglin_girl.bone.all.decendant","aj.piglin_girl.bone.all.decendant.locator","aj.piglin_girl.bone.all.tree","aj.piglin_girl.bone.body1.child","aj.piglin_girl.bone.body1.child.locator","aj.piglin_girl.bone.body1.decendant","aj.piglin_girl.bone.body1.decendant.locator","aj.piglin_girl.bone.body1.tree","aj.piglin_girl.entity","aj.piglin_girl.locator","aj.piglin_girl.locator.head_cheak","aj.piglin_girl.node","aj.piglin_girl.node.head_cheak"]}
execute as @n[ type=item_display, tag=aj.piglin_girl.locator.head_cheak, tag=aj.new, distance=..7 ] run function animated_java:piglin_girl/zzz/summon/as_data_entity/as_locator/head_cheak
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_head_cheak set from storage animated_java:gu out
data modify entity @s data.locators.head_cheak.uuid set from storage animated_java:gu out
summon item_display ^1.5 ^0 ^1 {Tags:["aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.camara1","aj.global.root.child","aj.global.root.child.locator","aj.new","aj.piglin_girl.entity","aj.piglin_girl.locator","aj.piglin_girl.locator.camara1","aj.piglin_girl.node","aj.piglin_girl.node.camara1"]}
execute as @n[ type=item_display, tag=aj.piglin_girl.locator.camara1, tag=aj.new, distance=..2 ] run function animated_java:piglin_girl/zzz/summon/as_data_entity/as_locator/camara1
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_camara1 set from storage animated_java:gu out
data modify entity @s data.locators.camara1.uuid set from storage animated_java:gu out
summon item_display ^-1.0625 ^2.1875 ^3 {Tags:["aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.camara2","aj.global.root.child","aj.global.root.child.locator","aj.new","aj.piglin_girl.entity","aj.piglin_girl.locator","aj.piglin_girl.locator.camara2","aj.piglin_girl.node","aj.piglin_girl.node.camara2"]}
execute as @n[ type=item_display, tag=aj.piglin_girl.locator.camara2, tag=aj.new, distance=..4 ] run function animated_java:piglin_girl/zzz/summon/as_data_entity/as_locator/camara2
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.locator_camara2 set from storage animated_java:gu out
data modify entity @s data.locators.camara2.uuid set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.chest] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_chest set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.tail2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tail2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.tail] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_tail set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.skirt] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_skirt set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.skirt1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_skirt1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.skirt2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_skirt2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.body1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.item_display] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.r_weapon] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_weapon set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.r2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.r1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.item_display1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.l2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.l1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.rl2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rl2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.rl1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_rl1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.ll2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_ll2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.piglin_girl.node.ll1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_ll1 set from storage animated_java:gu out