# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl/zzz/summon/locators_on_summon/zzz/0 with entity @s data.locators.head_cheak
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:piglin_girl/zzz/summon/locators_on_summon/zzz/1 with entity @s data.locators.camara1
data modify entity @s data.uuids append from storage animated_java:temp uuids
function animated_java:piglin_girl/zzz/summon/locators_on_summon/zzz/2 with entity @s data.locators.camara2
data modify entity @s data.uuids append from storage animated_java:temp uuids