# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.archdemon.animation.idle.playing
tag @s remove aj.archdemon.animation.idle_run.playing
tag @s remove aj.archdemon.animation.hellfire.playing
tag @s remove aj.archdemon.animation.hellfire_run.playing
tag @s remove aj.archdemon.animation.attack.playing
tag @s remove aj.archdemon.animation.attack_run.playing
tag @s remove aj.archdemon.animation.run.playing
tag @s remove aj.archdemon.animation.fly.playing
tag @s remove aj.archdemon.animation.jump_ready.playing
tag @s remove aj.archdemon.animation.jump_end.playing
tag @s remove aj.archdemon.animation.jump_ready_run.playing
tag @s remove aj.archdemon.animation.sprint_start.playing
tag @s remove aj.archdemon.animation.sprint_start_run.playing
tag @s remove aj.archdemon.animation.sprint_end.playing
tag @s remove aj.archdemon.animation.throw_ice.playing
tag @s remove aj.archdemon.animation.throw_ice_run.playing
tag @s remove aj.archdemon.animation.die.playing