# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:rat rig_hash set value '83254406569093deba37e0a9370cce2ee0b2946c07ad62e82de535952a17b597'
scoreboard objectives add aj.mutant_rat_standby.frame dummy
scoreboard objectives add aj.mutant_rat_walk.frame dummy