# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f25e5e36c9b9fa53ce3df2158ea317205e3b6135920be6c03231b01d5ec93b03'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack