# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl/animations/dagger_run2/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.dagger_run2.frame 1