# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @s on passengers if entity @s[tag=aj.global.data] run function animated_java:graud_golem/zzz/zzz/set_default_pose/as_locator_head with entity @s data.locators.head
execute at @s on passengers if entity @s[tag=aj.global.data] run function animated_java:graud_golem/zzz/zzz/set_default_pose/as_locator_leg1 with entity @s data.locators.leg1
execute at @s on passengers if entity @s[tag=aj.global.data] run function animated_java:graud_golem/zzz/zzz/set_default_pose/as_locator_leg2 with entity @s data.locators.leg2
execute at @s on passengers if entity @s[tag=aj.global.data] run function animated_java:graud_golem/zzz/zzz/set_default_pose/as_locator_leg3 with entity @s data.locators.leg3
execute at @s on passengers if entity @s[tag=aj.global.data] run function animated_java:graud_golem/zzz/zzz/set_default_pose/as_locator_leg4 with entity @s data.locators.leg4