# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_npc/root/on_tick/transform_locators
function animated_java:pink_npc/root/on_tick/select_camera_camera2 with entity @s data.cameras.camera2