# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:piglin_girl/animations/pause_all
tag @s add aj.piglin_girl.animation.dagger_attack3_end.playing
scoreboard players set @s aj.dagger_attack3_end.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:piglin_girl/animations/dagger_attack3_end/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only