# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_gopr/animations/pause_all
tag @s add aj.gray_gopr.animation.great_attack_4.playing
scoreboard players set @s aj.great_attack_4.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:gray_gopr/animations/great_attack_4/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only