# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.animation_model_new.frame matches 2.. run scoreboard players set @s aj.animation_model_new.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.animation_model_new.frame
execute at @s run function animated_java:rome_army/animations/animation_model_new/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.animation_model_new.frame 1