# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.uuid set from entity @s data.locators.head.uuid
function animated_java:graud_golem/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.leg1.uuid
function animated_java:graud_golem/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.leg2.uuid
function animated_java:graud_golem/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.leg3.uuid
function animated_java:graud_golem/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args
data modify storage animated_java:temp args.uuid set from entity @s data.locators.leg4.uuid
function animated_java:graud_golem/zzz/as_all_locators/execute_as_uuid with storage animated_java:temp args