# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:gray_coffin/remove/as_data/as_locator_hitbox1 with entity @s data.locators.hitbox1
function animated_java:gray_coffin/remove/as_data/as_locator_hitbox2 with entity @s data.locators.hitbox2
function animated_java:gray_coffin/remove/as_data/as_locator_hitbox3 with entity @s data.locators.hitbox3