# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:pink_white3/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.pink_white3.node.bone2] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0313f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pink_white3.node.bone1] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0156f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.pink_white3.node.bone] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0156f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }