# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.8542f,0f,0f,0f,0.4917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.2529f,-0.456f,3.205f,0f,-0.456f,-1.2529f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.2529f,-0.456f,3.205f,0f,-0.456f,-1.2529f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0.0011f,0f,1.1205f,-0.2394f,3.2652f,0f,-0.2394f,-1.1205f,-0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1359f,0f,2f,0f,0f,-1.0833f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1.9159f,0f,0.7638f,-0.2544f,0f,2.0625f,0f,3.1324f,-0.7638f,0f,-1.9159f,-0.8707f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-1.9604f,0f,-0.7815f,0.2413f,0f,2.1104f,0f,3.1324f,0.7815f,0f,-1.9604f,-0.8793f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0.001071673525377158,"py":3.5180116420282337,"pz":0.5807975566042127,"ry":0,"rx":-12.061042524005487}}}