# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.7408f,0f,0f,0f,0.1503f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3333f,0f,0f,-1f,0f,1.326f,-0.1394f,3.1704f,0f,-0.1394f,-1.326f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3333f,0f,0f,1f,0f,1.326f,-0.1394f,3.1704f,0f,-0.1394f,-1.326f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0.0002f,0f,0.9909f,-0.5754f,3.2793f,0f,-0.5754f,-0.9909f,-0.0007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.1849f,0f,2f,0f,0f,-1.0833f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1.5566f,0f,1.3532f,-0.2507f,0f,2.0625f,0f,3.1396f,-1.3532f,0f,-1.5566f,-0.8743f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-1.5927f,0f,-1.3846f,0.2485f,0f,2.1104f,0f,3.1396f,1.3846f,0f,-1.5927f,-0.8757f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":0.00018084490740734893,"py":3.7012576257863414,"pz":0.476978540814309,"ry":0,"rx":-30.144675925925924}}}