# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1567f,-0.1523f,0f,0.375f,-0.1523f,1.1567f,0f,1.375f,0f,0f,-1.1667f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1257f,0.1482f,0f,-0.375f,0.1482f,1.1257f,0f,1.375f,0f,0f,-1.1354f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1.3111f,0f,0f,0f,1.7846f,0f,0f,0f,-0.7017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3017f,0.2886f,0f,-1f,0.2499f,1.1273f,0.6667f,3f,0.1443f,0.6509f,-1.1547f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3017f,-0.2886f,0f,1f,-0.2499f,1.1273f,0.6667f,3f,-0.1443f,0.6509f,-1.1547f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,0f,0f,1.1284f,0.199f,3.25f,0f,0.199f,-1.1284f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0833f,0f,0f,0f,0f,1.0823f,0.0473f,2f,0f,0.0473f,-1.0823f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-1.9381f,0f,-0.7054f,-0.25f,0f,2.0625f,0f,3.125f,0.7054f,0f,-1.9381f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-1.9831f,0f,0.7218f,0.25f,0f,2.1104f,0f,3.125f,-0.7218f,0f,-1.9831f,-0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-7.803582496833832e-17,"py":3.2645708580846944,"pz":0.6372108678409962,"ry":0,"rx":10.000000000000002}}}