# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:sword_double_model rig_hash set value 'f1324b751ebd0244cd64e883d771e4dae2e290758ad2fca77c3a2df213d1f85d'
scoreboard objectives add aj.attack_test.frame dummy
scoreboard objectives add aj.attack_test2.frame dummy
scoreboard objectives add aj.attack_test3.frame dummy
scoreboard objectives add aj.attack_test4.frame dummy
scoreboard objectives add aj.run.frame dummy
scoreboard objectives add aj.run_stop.frame dummy
scoreboard objectives add aj.run_keep.frame dummy