# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1667f,0f,1.375f,0f,0f,-1.1667f,0.0996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.0675f,0.3869f,1.375f,0f,0.3869f,-1.0675f,-0.0996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5127f,0f,0f,0f,-0.0996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-0.9934f,0f,0.8893f,-1f,0f,1.3333f,0f,2.9502f,-0.8893f,0f,-0.9934f,-0.0996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3044f,0f,0.2761f,0.9502f,0f,1.3333f,0f,3f,-0.2761f,0f,-1.3044f,0.1494f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,-0.0125f,0f,1.1396f,0.1193f,3.2373f,0f,0.1193f,-1.1396f,0.0879f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0598f,0f,0.2244f,0f,0f,1.0833f,0f,2f,-0.2244f,0f,-1.0598f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0625f,0f,0f,-0.1987f,0f,2.0625f,0f,3.127f,0f,0f,-2.0625f,-0.9253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.1104f,0f,0f,0.3511f,0f,2.1104f,0f,3.127f,0f,0f,-2.1104f,-0.8247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-0.012451171875000088,"py":3.296549237671748,"pz":0.7225086859429164,"ry":0,"rx":5.9765625}}}