# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1667f,0f,1.375f,0f,0f,-1.1667f,0.0818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.0895f,0.3198f,1.375f,0f,0.3198f,-1.0895f,-0.0818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5216f,0f,0f,0f,-0.0818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.1008f,0f,0.7523f,-1f,0f,1.3333f,0f,2.9591f,-0.7523f,0f,-1.1008f,-0.0818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3138f,0f,0.2273f,0.9591f,0f,1.3333f,0f,3f,-0.2273f,0f,-1.3138f,0.1227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,-0.0102f,0f,1.1416f,0.098f,3.2284f,0f,0.098f,-1.1416f,0.1057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0675f,0f,0.1847f,0f,0f,1.0833f,0f,2f,-0.1847f,0f,-1.0675f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0625f,0f,0f,-0.2079f,0f,2.0625f,0f,3.1266f,0f,0f,-2.0625f,-0.9163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.1104f,0f,0f,0.333f,0f,2.1104f,0f,3.1266f,0f,0f,-2.1104f,-0.8337f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-0.01022338867187509,"py":3.299471251039352,"pz":0.7391147860131603,"ry":0,"rx":4.9072265625}}}