# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1667f,0f,1.375f,0f,0f,-1.1667f,0.0432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.1225f,0.1706f,1.375f,0f,0.1706f,-1.1225f,-0.0432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5409f,0f,0f,0f,-0.0432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.267f,0f,0.4153f,-1f,0f,1.3333f,0f,2.9784f,-0.4153f,0f,-1.267f,-0.0432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.3279f,0f,0.1205f,0.9784f,0f,1.3333f,0f,3f,-0.1205f,0f,-1.3279f,0.0648f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,-0.0054f,0f,1.1447f,0.0518f,3.2091f,0f,0.0518f,-1.1447f,0.1443f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0789f,0f,0.0979f,0f,0f,1.0833f,0f,2f,-0.0979f,0f,-1.0789f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0625f,0f,0f,-0.2277f,0f,2.0625f,0f,3.1259f,0f,0f,-2.0625f,-0.8968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.1104f,0f,0f,0.2939f,0f,2.1104f,0f,3.1259f,0f,0f,-2.1104f,-0.8532f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-0.0054016113281250945,"py":3.305705361795306,"pz":0.7743019102601443,"ry":0,"rx":2.5927734375}}}