# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left_leg) {transformation: [-1.1667f,0f,0f,0.375f,0f,1.1667f,0f,1.375f,0f,0f,-1.1667f,0.0105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1.1354f,0f,0f,-0.375f,0f,1.1347f,0.0416f,1.375f,0f,0.0416f,-1.1347f,-0.0105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1f,0f,0f,0f,1.5573f,0f,0f,0f,-0.0105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_hand) {transformation: [-1.3294f,0f,0.1025f,-1f,0f,1.3333f,0f,2.9948f,-0.1025f,0f,-1.3294f,-0.0105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_hand) {transformation: [-1.333f,0f,0.0293f,0.9948f,0f,1.3333f,0f,3f,-0.0293f,0f,-1.333f,0.0157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1.1458f,0f,0f,-0.0013f,0f,1.1458f,0.0126f,3.1927f,0f,0.0126f,-1.1458f,0.177f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0831f,0f,0.0238f,0f,0f,1.0833f,0f,2f,-0.0238f,0f,-1.0831f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-2.0625f,0f,0f,-0.2446f,0f,2.0625f,0f,3.1252f,0f,0f,-2.0625f,-0.8803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-2.1104f,0f,0f,0.2607f,0f,2.1104f,0f,3.1252f,0f,0f,-2.1104f,-0.8697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"locator":{"px":-0.001312255859375102,"py":3.310870652696662,"pz":0.8033383489229459,"ry":0,"rx":0.6298828125}}}